//! The emitted crate's manifest.
//!
//! Written as text rather than through a TOML serializer: a manifest is a handful of lines whose
//! exact shape a reader of a checked-in generated crate will look at, and the dependency list is
//! computed from what the types actually use — a generated crate that declares `chrono` because the
//! configuration mentions it, and then never names it, is a compile cost nobody asked for.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::api::{ApiModel, BodyContract};
use crate::config::{BytesRepr, Config, DateTimeCrate, MapKind, UuidCrate};
use crate::contract::{Contracts, TypeRef};
use crate::shape::Format;

/// The `reqwest` features a generated client forwards, and whether it turns each on by default.
///
/// Every name is forwarded under itself, so a consumer reads the generated manifest and gets the
/// feature they already know from `reqwest`. `native-tls` is the one that is off: it is the
/// alternative to `rustls`, not an addition to it.
const REQWEST_FEATURES: [(&str, bool); 5] = [
    ("rustls", true),
    ("native-tls", false),
    ("http2", true),
    ("charset", true),
    ("system-proxy", true),
];

pub(super) fn render(
    contracts: &Contracts,
    api: &ApiModel,
    config: &Config,
    client: bool,
    server: bool,
    streams: bool,
) -> String {
    // The one place `::bytes::Bytes` is spelled is the client's builder for a binary body, so the
    // dependency exists exactly when that spelling does.
    let bytes = client
        && config.formats.bytes == BytesRepr::Bytes
        && api
            .operations()
            .iter()
            .any(|operation| matches!(operation.body, Some(BodyContract::Bytes { .. })));
    let mut out = String::new();
    out.push_str("# Generated by progeny. Edits are overwritten on the next run.\n");
    out.push_str("[package]\n");
    let _ = writeln!(out, "name = {:?}", config.package.name);
    let _ = writeln!(out, "version = {:?}", config.package.version);
    out.push_str("edition = \"2021\"\n");
    out.push_str(indoc::indoc! {"
        publish = false

    "});

    if client || server {
        // Each half is a feature so that a consumer of one does not compile the other's HTTP stack.
        // Both are on by default because progeny only emits a module when it was asked to; turning
        // one off is `default-features = false` plus the half that is wanted.
        out.push_str("[features]\n");
        let mut default: Vec<&str> = [("client", client), ("server", server)]
            .into_iter()
            .filter_map(|(name, wanted)| wanted.then_some(name))
            .collect();
        if client {
            let on = REQWEST_FEATURES
                .iter()
                .filter_map(|(name, on_by_default)| on_by_default.then_some(*name));
            default.extend(on);
        }
        let _ = writeln!(out, "default = [{}]", quoted(&default));
        if client {
            let mut wants = vec!["dep:reqwest"];
            // The stream helpers ride on the client feature, because a stream is a way of calling
            // the operation and there is nothing to call without it.
            if streams {
                wants.extend(["dep:futures-core", "dep:futures-util"]);
            }
            if bytes {
                wants.push("dep:bytes");
            }
            let _ = writeln!(out, "client = [{}]", quoted(&wants));
        }
        if server {
            out.push_str("server = [\"dep:axum\", \"dep:tokio\"]\n");
        }
        if client {
            // `reqwest` is public here — the consumer hands `with_client` a `Client` and gets one
            // back from `client()` — so which TLS backend, HTTP version and proxy source it is
            // built with is their decision. Feature unification alone cannot express that: it only
            // ever adds, so a stack named here is one a consumer can never drop. Forwarding gives
            // the choice an off switch, and `default` keeps the crate working untouched.
            for (name, _) in REQWEST_FEATURES {
                let _ = writeln!(out, "{name} = [\"reqwest?/{name}\"]");
            }
        }
        out.push('\n');
    }

    out.push_str("[dependencies]\n");
    out.push_str("serde = { version = \"1\", features = [\"derive\"] }\n");
    out.push_str("serde_json = \"1\"\n");
    if client || server {
        out.push_str("indoc = \"2\"\n");
        out.push_str("thiserror = \"2\"\n");
    }
    if client {
        out.push_str(
            // Only the two features the emitted calls name; the rest are the consumer's, forwarded
            // through this crate's own features.
            "reqwest = { version = \"0.13\", optional = true, default-features = false, \
             features = [\"json\", \"query\"] }\n",
        );
        // Only when something declared pagination. A crate that did not ask for streams must not
        // pay to compile them, which is the same rule the two halves already follow.
        if streams {
            out.push_str("futures-core = { version = \"0.3\", optional = true }\n");
            out.push_str(
                "futures-util = { version = \"0.3\", optional = true, default-features = false }\n",
            );
        }
        if bytes {
            out.push_str("bytes = { version = \"1\", optional = true }\n");
        }
    }
    if server {
        // `axum` is the router the registrability classifier asked at generation time; a different
        // major here would mean the routes were checked against a router this crate does not use.
        out.push_str("axum = { version = \"0.8\", optional = true }\n");
        // A handler is an `async fn`, so a generated server needs a runtime to be worth having.
        // Only `rt` and `macros`: which flavour and how many threads is the service's decision.
        out.push_str(
            "tokio = { version = \"1\", optional = true, default-features = false, \
             features = [\"rt\", \"macros\"] }\n",
        );
    }
    for line in extra_dependencies(contracts, api, config) {
        let _ = writeln!(out, "{line}");
    }
    out
}

/// The dependencies the rendered surface actually names.
fn extra_dependencies(contracts: &Contracts, api: &ApiModel, config: &Config) -> Vec<String> {
    let mut formats = BTreeSet::new();
    let mut maps = false;
    for contract in contracts.types() {
        for ty in contract.kind().references() {
            collect(ty, &mut formats, &mut maps);
        }
    }
    // The API surface names types the contract list does not: a scalar parameter or an inline
    // response gets no named contract on purpose — a `pub type` alias for one scalar would be
    // noise — but its `TypeRef` still renders to `uuid::Uuid` or the configured map in the
    // builder and the trait, and a manifest that missed it shipped a crate that cannot compile.
    for operation in api.operations() {
        for param in &operation.params {
            collect(&param.ty, &mut formats, &mut maps);
        }
        if let Some(ty) = operation.body.as_ref().and_then(BodyContract::ty) {
            collect(ty, &mut formats, &mut maps);
        }
        let arms = operation.responses.arms.iter();
        for arm in arms.chain(operation.responses.default.as_ref()) {
            collect(&arm.ty, &mut formats, &mut maps);
        }
    }

    let mut lines = Vec::new();
    let dates = formats.contains(&Format::DateTime)
        || formats.contains(&Format::Date)
        || formats.contains(&Format::Time);
    if dates {
        match config.formats.date_time {
            DateTimeCrate::String => {}
            DateTimeCrate::Chrono => {
                lines.push("chrono = { version = \"0.4\", features = [\"serde\"] }".to_owned());
            }
            DateTimeCrate::Time => {
                lines.push("time = { version = \"0.3\", features = [\"serde\"] }".to_owned());
            }
            DateTimeCrate::Jiff => {
                lines.push("jiff = { version = \"0.2\", features = [\"serde\"] }".to_owned());
            }
        }
    }
    if formats.contains(&Format::Uuid) {
        match config.formats.uuid {
            UuidCrate::String => {}
            UuidCrate::Uuid => {
                lines.push("uuid = { version = \"1\", features = [\"serde\"] }".to_owned());
            }
        }
    }
    if config.map == MapKind::IndexMap && maps {
        lines.push("indexmap = { version = \"2\", features = [\"serde\"] }".to_owned());
    }
    lines
}

fn collect(ty: &TypeRef, formats: &mut BTreeSet<Format>, maps: &mut bool) {
    match ty {
        TypeRef::Format(format) => {
            formats.insert(*format);
        }
        TypeRef::Map(inner) => {
            *maps = true;
            collect(inner, formats, maps);
        }
        TypeRef::Option(inner)
        | TypeRef::Vec(inner)
        | TypeRef::Boxed(inner)
        | TypeRef::Array(inner, _) => collect(inner, formats, maps),
        TypeRef::Tuple(items) => {
            for item in items {
                collect(item, formats, maps);
            }
        }
        _ => {}
    }
}

/// A TOML string list.
fn quoted(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("{name:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}
