//! The emitted crate's manifest.
//!
//! Written as text rather than through a TOML serializer: a manifest is a handful of lines whose
//! exact shape a reader of a checked-in generated crate will look at, and the dependency list is
//! computed from what the types actually use — a generated crate that declares `chrono` because the
//! configuration mentions it, and then never names it, is a compile cost nobody asked for.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::config::{Config, DateTimeCrate, MapKind, UuidCrate};
use crate::contract::{ContractKind, Contracts, TypeRef};
use crate::shape::Format;

pub(super) fn render(contracts: &Contracts, config: &Config) -> String {
    let mut out = String::new();
    out.push_str("# Generated by progeny. Edits are overwritten on the next run.\n");
    out.push_str("[package]\n");
    let _ = writeln!(out, "name = {:?}", config.package.name);
    let _ = writeln!(out, "version = {:?}", config.package.version);
    out.push_str("edition = \"2021\"\n");
    out.push_str("publish = false\n\n");

    out.push_str("[dependencies]\n");
    out.push_str("serde = { version = \"1\", features = [\"derive\"] }\n");
    out.push_str("serde_json = \"1\"\n");
    for line in extra_dependencies(contracts, config) {
        let _ = writeln!(out, "{line}");
    }
    out
}

/// The dependencies the rendered types actually name.
fn extra_dependencies(contracts: &Contracts, config: &Config) -> Vec<String> {
    let mut formats = BTreeSet::new();
    for contract in contracts.types() {
        for ty in references(contract.kind()) {
            collect(ty, &mut formats);
        }
    }

    let mut lines = Vec::new();
    let dates = formats.contains(&Format::DateTime)
        || formats.contains(&Format::Date)
        || formats.contains(&Format::Time);
    if dates {
        match config.formats.date_time {
            DateTimeCrate::String => {}
            DateTimeCrate::Chrono => {
                lines.push("chrono = { version = \"0.4\", features = [\"serde\"] }".to_owned());
            }
            DateTimeCrate::Time => {
                lines.push("time = { version = \"0.3\", features = [\"serde\"] }".to_owned());
            }
            DateTimeCrate::Jiff => {
                lines.push("jiff = { version = \"0.2\", features = [\"serde\"] }".to_owned());
            }
        }
    }
    if formats.contains(&Format::Uuid) {
        match config.formats.uuid {
            UuidCrate::String => {}
            UuidCrate::Uuid => {
                lines.push("uuid = { version = \"1\", features = [\"serde\"] }".to_owned());
            }
        }
    }
    if config.map == MapKind::IndexMap && uses_map(contracts) {
        lines.push("indexmap = { version = \"2\", features = [\"serde\"] }".to_owned());
    }
    lines
}

fn collect(ty: &TypeRef, formats: &mut BTreeSet<Format>) {
    match ty {
        TypeRef::Format(format) => {
            formats.insert(*format);
        }
        TypeRef::Option(inner)
        | TypeRef::Vec(inner)
        | TypeRef::Map(inner)
        | TypeRef::Boxed(inner)
        | TypeRef::Array(inner, _) => collect(inner, formats),
        TypeRef::Tuple(items) => {
            for item in items {
                collect(item, formats);
            }
        }
        _ => {}
    }
}

fn uses_map(contracts: &Contracts) -> bool {
    contracts
        .types()
        .iter()
        .flat_map(|contract| references(contract.kind()))
        .any(is_map)
}

fn is_map(ty: &TypeRef) -> bool {
    match ty {
        TypeRef::Map(_) => true,
        TypeRef::Option(inner)
        | TypeRef::Vec(inner)
        | TypeRef::Boxed(inner)
        | TypeRef::Array(inner, _) => is_map(inner),
        TypeRef::Tuple(items) => items.iter().any(is_map),
        _ => false,
    }
}

fn references(kind: &ContractKind) -> Vec<&TypeRef> {
    match kind {
        ContractKind::Struct { fields } => fields.iter().map(|field| &field.ty).collect(),
        ContractKind::Enum { variants } => variants.iter().map(|variant| &variant.ty).collect(),
        ContractKind::StringEnum { .. } => Vec::new(),
        ContractKind::Newtype { inner } | ContractKind::Alias { target: inner } => vec![inner],
        ContractKind::Tuple { items } => items.iter().collect(),
    }
}
