//! Rendering: pure functions from frozen contracts to source text.
//!
//! Two packagings of one rendering. **Crate mode** writes a manifest and a `src` tree; **module
//! mode** writes the same modules nested into a single file, for `include!` from a build script or
//! for checking in. One renderer, two wrappers, no forked logic — so a change to how a type is
//! written cannot land in one packaging and not the other.
//!
//! **Determinism is an output invariant**: the same document, configuration and progeny version
//! render byte-identical source. Everything here iterates `BTreeMap`s and `Vec`s in a fixed order,
//! and the corpus harness generates every document twice per run and compares.

// `client`, `server` and `types` are crate-visible rather than private because the probe harness
// reuses their naming — type paths, group and response names — instead of growing a second copy
// that could drift from what is actually rendered.
pub(crate) mod client;
mod manifest;
mod serde_impl;
pub(crate) mod server;
pub(crate) mod types;

use std::collections::BTreeMap;

use camino::Utf8PathBuf;
use proc_macro2::TokenStream;
use quote::quote;

use crate::api::ApiModel;
use crate::config::{Config, Packaging};
use crate::contract::Contracts;

/// Render the contracts and the API model into the files a caller writes out.
pub(crate) fn run(
    contracts: &Contracts,
    api: &ApiModel,
    config: &Config,
) -> BTreeMap<Utf8PathBuf, String> {
    let mut files = BTreeMap::new();
    if !config.emit.types {
        return files;
    }
    let mut body = types::render(contracts, config);
    body.extend(serde_impl::render(contracts));
    let mut modules = vec![("types", body)];

    // An operation nobody can call is not worth a module: a description with no paths generates a
    // type layer and stops there, rather than emitting a `Client` with no methods and the whole
    // HTTP dependency behind it.
    let has_operations = !api.operations().is_empty();
    let http = config.emit.client && has_operations;
    // Whether any operation declared pagination, which is what decides whether the generated crate
    // depends on the stream machinery at all.
    let streams = http
        && api
            .operations()
            .iter()
            .any(|operation| operation.pagination.is_some());
    if http {
        modules.push(("client", client::render(api, contracts, config)));
    }
    // The same rule on the serving side, with one extra condition: a description whose every route
    // the router refused has no trait methods to implement, and a trait nobody can implement is not
    // a module.
    let serves = config.emit.server
        && api
            .operations()
            .iter()
            .any(|operation| operation.registrable.is_some());
    if serves {
        modules.push(("server", server::render(api, contracts, config)));
    }
    // Emitted only when something calls into it: an unused module is compile time the consumer did
    // not ask for.
    if http || serves || serde_impl::needed(contracts) {
        modules.push((
            "support",
            crate::support::tokens(
                http,
                serves,
                config.packaging == Packaging::Crate,
                config.body_limit,
            ),
        ));
    }

    match config.packaging {
        Packaging::Crate => {
            files.insert(
                Utf8PathBuf::from("Cargo.toml"),
                manifest::render(contracts, config, http, serves, streams),
            );
            let declarations = modules.iter().map(|(name, _)| {
                let ident = quote::format_ident!("{name}");
                // The support module is not part of the generated crate's public API; it is
                // reachable because the type modules call into it and for no other reason.
                let hidden = (*name == "support").then(|| quote! { #[doc(hidden)] });
                let gated = match *name {
                    "client" => quote! { #[cfg(feature = "client")] },
                    "server" => quote! { #[cfg(feature = "server")] },
                    _ => quote! {},
                };
                quote! { #hidden #gated pub mod #ident; }
            });
            files.insert(
                Utf8PathBuf::from("src/lib.rs"),
                source(&quote! {
                    #![doc = " Generated by progeny. Edits are overwritten on the next run."]
                    #(#declarations)*
                }),
            );
            for (name, tokens) in modules {
                files.insert(Utf8PathBuf::from(format!("src/{name}.rs")), source(&tokens));
            }
        }
        Packaging::Module => {
            let nested = modules.into_iter().map(|(name, tokens)| {
                let ident = quote::format_ident!("{name}");
                let hidden = (name == "support").then(|| quote! { #[doc(hidden)] });
                quote! { #hidden pub mod #ident { #tokens } }
            });
            files.insert(
                Utf8PathBuf::from("progeny.rs"),
                source(&quote! {
                    #![doc = " Generated by progeny. Edits are overwritten on the next run."]
                    #(#nested)*
                }),
            );
        }
    }
    files
}

/// Format a token stream as source text.
///
/// `prettyplease` rather than rustfmt: a formatter that runs in-process needs no toolchain at
/// generation time and cannot be missing. A stream that does not parse as a file falls back to the
/// token text, which is still valid Rust and still compiles — a formatting failure must not be able
/// to fail a build.
fn source(tokens: &TokenStream) -> String {
    match syn::parse2::<syn::File>(tokens.clone()) {
        Ok(file) => prettyplease::unparse(&file),
        Err(_) => tokens.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use serde_json::{Value, json};

    use crate::config::{Config, Packaging, SerdeImpl};
    use crate::diag::Ctx;
    use crate::doc::parse as doc_parse;
    use crate::{contract, normalize, resolve, shape};

    /// Generate the types module for a document.
    fn types(document: Value, config: &Config) -> String {
        let mut ctx = Ctx::new();
        let normalized = normalize::normalize(document, &mut ctx).unwrap();
        let parsed = doc_parse::document(normalized, &mut ctx);
        let resolved = resolve::resolve(parsed, &mut ctx);
        let shapes = shape::classify(&resolved, &mut ctx);
        let contracts = contract::build(&resolved, &shapes, config, &mut ctx).unwrap();
        let api = crate::api::build(&resolved, &shapes, &contracts, config, &mut ctx).unwrap();
        let files = super::run(&contracts, &api, config);
        files
            .get(camino::Utf8Path::new("src/types.rs"))
            .cloned()
            .unwrap_or_default()
    }

    /// Generate the client module for a document.
    fn client(document: Value) -> String {
        let config = Config::default();
        let mut ctx = Ctx::new();
        let normalized = normalize::normalize(document, &mut ctx).unwrap();
        let parsed = doc_parse::document(normalized, &mut ctx);
        let resolved = resolve::resolve(parsed, &mut ctx);
        let shapes = shape::classify(&resolved, &mut ctx);
        let contracts = contract::build(&resolved, &shapes, &config, &mut ctx).unwrap();
        let api = crate::api::build(&resolved, &shapes, &contracts, &config, &mut ctx).unwrap();
        let files = super::run(&contracts, &api, &config);
        let rendered = files
            .get(camino::Utf8Path::new("src/client.rs"))
            .cloned()
            .unwrap_or_default();
        // The renderer falls back to unformatted tokens when a stream does not parse, which is the
        // right call for a build and the wrong one for a test that then greps the text.
        syn::parse_file(&rendered).expect("the client module should parse");
        rendered
    }

    /// The escape hatch, named rather than defaulted to.
    ///
    /// The serde attributes only exist in this mode: they are helper attributes of the derive
    /// macros, so a type on the hand-written path carries none at all. A test about how an
    /// attribute renders has to say which mode it is about, and these did not until the default
    /// changed under them.
    fn derive_mode() -> Config {
        Config {
            serde_impl: crate::config::SerdeImpl::DeriveAlways,
            ..Config::default()
        }
    }

    fn with_schemas(schemas: Value) -> Value {
        // Built member by member rather than with `json!`, which would only borrow `schemas`.
        let mut components = serde_json::Map::new();
        components.insert("schemas".to_owned(), schemas);
        let mut root = serde_json::Map::new();
        root.insert("openapi".to_owned(), Value::String("3.1.0".to_owned()));
        root.insert("paths".to_owned(), Value::Object(serde_json::Map::new()));
        root.insert("components".to_owned(), Value::Object(components));
        Value::Object(root)
    }

    #[test]
    fn a_struct_renders_with_its_wire_names_and_its_docs() {
        let rendered = types(
            with_schemas(json!({
                "Pet": {
                    "type": "object",
                    "description": "One pet.",
                    "required": ["petName"],
                    "properties": {
                        "petName": {"type": "string", "description": "What it answers to."},
                        "type": {"type": "string"},
                        "tags": {"type": "array", "items": {"type": "string"}},
                    },
                },
            })),
            &derive_mode(),
        );
        assert!(rendered.contains("pub struct Pet {"), "{rendered}");
        assert!(rendered.contains("/// One pet."), "{rendered}");
        assert!(rendered.contains("/// What it answers to."), "{rendered}");
        // Case conversion on the Rust side, the wire name kept exactly.
        assert!(
            rendered.contains(r#"#[serde(rename = "petName")]"#),
            "{rendered}"
        );
        assert!(rendered.contains("pub pet_name: String"), "{rendered}");
        // A reserved word is renamed with a suffix, and says what it was.
        assert!(rendered.contains(r#"rename = "type""#), "{rendered}");
        assert!(rendered.contains("pub type_: Option<String>"), "{rendered}");
        assert!(
            rendered.contains(r#"skip_serializing_if = "Option::is_none""#),
            "{rendered}"
        );
        assert!(
            rendered.contains("pub tags: Option<Vec<String>>"),
            "{rendered}"
        );
    }

    /// A type on the hand-written path carries **no** `#[serde(...)]` attributes at all.
    ///
    /// Mandatory rather than tidy, and in two directions. They are helper attributes of the serde
    /// derive macros, so with no derive on the item they do not resolve and the crate does not
    /// compile. And any *other* derive that reads them would then see a different type than the wire
    /// format has — `schemars::JsonSchema` honours `rename` and `skip_serializing_if`, so a schema
    /// generated beside a hand-written impl would disagree with the bytes. That is the forbidden
    /// failure mode, and it is why `DeriveSet` is a closed set of attribute-blind derives.
    ///
    /// The wire name has to survive the move: it stops being an attribute and becomes a string in
    /// the generated impl, and this checks it is still there rather than merely gone from the type.
    #[test]
    fn a_hand_written_type_carries_no_serde_attributes_and_keeps_its_wire_name() {
        let document = with_schemas(json!({
            "Pet": {
                "type": "object",
                "required": ["petName"],
                "properties": {
                    "petName": {"type": "string"},
                    "type": {"type": "string"},
                },
            },
        }));
        let rendered = types(document, &Config::default());
        assert!(rendered.contains("pub struct Pet {"), "{rendered}");
        assert!(
            !rendered.contains("#[serde("),
            "a hand-written type kept a serde attribute:\n{rendered}"
        );
        assert!(
            !rendered.contains("derive(serde::Deserialize"),
            "a hand-written type kept the derive:\n{rendered}"
        );
        // The wire names moved into the impl rather than being lost with the attributes.
        assert!(rendered.contains(r#""petName""#), "{rendered}");
        assert!(rendered.contains("pub pet_name: String"), "{rendered}");
        assert!(rendered.contains("pub type_: Option<String>"), "{rendered}");
    }

    #[test]
    fn the_rendered_source_parses_as_rust() {
        // Formatting is what proves the stream is syntactically valid: `prettyplease` only runs on
        // a `syn::File`, and the fallback would leave the tokens on one line.
        let rendered = types(
            with_schemas(json!({
                "Pet": {"type": "object", "properties": {"name": {"type": "string"}}},
            })),
            &Config::default(),
        );
        syn::parse_file(&rendered).unwrap();
        assert!(rendered.lines().count() > 3, "{rendered}");
    }

    #[test]
    fn a_fieldless_enum_keeps_the_bytes_it_had() {
        let rendered = types(
            with_schemas(json!({
                "State": {"type": "string", "enum": ["in-progress", "done", "2fa"]},
            })),
            &derive_mode(),
        );
        assert!(rendered.contains("pub enum State"), "{rendered}");
        assert!(
            rendered.contains(r#"#[serde(rename = "in-progress")]"#),
            "{rendered}"
        );
        assert!(rendered.contains("InProgress,"), "{rendered}");
        assert!(rendered.contains("_2fa,"), "{rendered}");
    }

    #[test]
    fn a_union_renders_untagged() {
        let rendered = types(
            with_schemas(json!({
                "Either": {"oneOf": [{"type": "string"}, {"type": "integer"}]},
            })),
            &Config::default(),
        );
        assert!(rendered.contains("#[serde(untagged)]"), "{rendered}");
        assert!(rendered.contains("Text(String)"), "{rendered}");
        assert!(rendered.contains("Integer(i64)"), "{rendered}");
    }

    #[test]
    fn a_union_that_shape_cannot_decide_renders_its_tag() {
        let rendered = types(
            with_schemas(json!({
                "Cat": {"type": "object", "properties": {"kind": {"type": "string"}, "shared": {"type": "string"}}},
                "Dog": {"type": "object", "properties": {"kind": {"type": "string"}, "shared": {"type": "string"}}},
                "Animal": {
                    "oneOf": [
                        {"$ref": "#/components/schemas/Cat"},
                        {"$ref": "#/components/schemas/Dog"},
                    ],
                    "discriminator": {"propertyName": "kind", "mapping": {"a cat": "#/components/schemas/Cat"}},
                },
            })),
            &Config::default(),
        );
        assert!(rendered.contains(r#"#[serde(tag = "kind")]"#), "{rendered}");
        assert!(rendered.contains("pub enum Animal"), "{rendered}");
        // The mapped name where the document gave one, the component name where it did not.
        assert!(
            rendered.contains(r#"#[serde(rename = "a cat")]"#),
            "{rendered}"
        );
        assert!(rendered.contains("ACat(Cat)"), "{rendered}");
        assert!(rendered.contains("Dog(Dog)"), "{rendered}");
        // And the property serde consumes is gone from the variants, because a variant that still
        // declared it would be handed a payload the tag had already been taken out of.
        assert!(!rendered.contains("pub kind:"), "{rendered}");
        assert!(
            rendered.contains("pub shared: Option<String>"),
            "{rendered}"
        );
    }

    #[test]
    fn a_declared_default_is_documented_rather_than_applied_on_the_way_in() {
        let rendered = types(
            with_schemas(json!({
                "Options": {
                    "type": "object",
                    "properties": {
                        "limit": {"type": "integer", "default": 20},
                        "name": {"type": "string", "default": "unnamed"},
                    },
                },
            })),
            &Config::default(),
        );
        // `#[serde(default = "…")]` would fill the member in on the way *in*, and it would then be
        // written on the way *out* — turning "the caller said nothing" into "the caller said 20" on
        // every request. The payload gate caught exactly that over the corpus.
        assert!(!rendered.contains("default = "), "{rendered}");
        assert!(!rendered.contains("fn default_options_limit"), "{rendered}");
        // Nothing is lost quietly: the server's assumption is stated where a reader will find it.
        assert!(
            rendered.contains("The server assumes `20` when this member is absent."),
            "{rendered}"
        );
        assert!(
            rendered.contains(r#"The server assumes `"unnamed"` when this member is absent."#),
            "{rendered}"
        );
        // And an absent member still deserializes, because every optional field is an `Option`.
        assert!(rendered.contains("pub limit: Option<i64>"), "{rendered}");
    }

    #[test]
    fn the_hand_written_strategy_leaves_no_serde_attributes_behind() {
        // Attributes are helper attributes of the serde derive macros: with no derive on the item
        // they do not even resolve, so leaving one behind would not compile.
        let config = Config {
            serde_impl: SerdeImpl::HandWrittenWhereEligible,
            ..Config::default()
        };
        let rendered = types(
            with_schemas(json!({
                "Pet": {"type": "object", "properties": {"petName": {"type": "string"}}},
            })),
            &config,
        );
        assert!(!rendered.contains("#[serde("), "{rendered}");
        assert!(!rendered.contains("#[derive(serde::"), "{rendered}");
        assert!(
            rendered.contains("pub pet_name: Option<String>"),
            "{rendered}"
        );
        // Two function bodies per type, calling into the machinery that lives once per crate.
        assert!(
            rendered.contains("impl<'de> serde::Deserialize<'de> for Pet"),
            "{rendered}"
        );
        assert!(
            rendered.contains("impl serde::Serialize for Pet"),
            "{rendered}"
        );
        assert!(
            rendered.contains("super::support::BufferVisitor"),
            "{rendered}"
        );
    }

    #[test]
    fn crate_mode_and_module_mode_render_the_same_types() {
        let document = with_schemas(json!({
            "Pet": {"type": "object", "properties": {"name": {"type": "string"}}},
        }));
        let as_crate = types(document.clone(), &Config::default());
        let module = Config {
            packaging: Packaging::Module,
            ..Config::default()
        };
        let mut ctx = Ctx::new();
        let normalized = normalize::normalize(document, &mut ctx).unwrap();
        let parsed = doc_parse::document(normalized, &mut ctx);
        let resolved = resolve::resolve(parsed, &mut ctx);
        let shapes = shape::classify(&resolved, &mut ctx);
        let contracts = contract::build(&resolved, &shapes, &module, &mut ctx).unwrap();
        let api = crate::api::build(&resolved, &shapes, &contracts, &module, &mut ctx).unwrap();
        let files = super::run(&contracts, &api, &module);
        assert_eq!(files.len(), 1);
        let nested = files
            .get(camino::Utf8Path::new("progeny.rs"))
            .cloned()
            .unwrap_or_default();
        assert!(nested.contains("pub mod types"), "{nested}");
        // The same struct, indented into a module: one renderer behind both packagings.
        assert!(nested.contains("pub struct Pet"), "{nested}");
        assert!(as_crate.contains("pub struct Pet"), "{as_crate}");
    }

    #[test]
    fn a_path_parameter_is_filled_in_and_refused_when_it_was_never_set() {
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets/{petId}": {"get": {
                "operationId": "showPetById",
                "parameters": [{"name": "petId", "in": "path", "required": true, "schema": {"type": "string"}}],
                "responses": {"200": {"description": "ok"}},
            }}},
        }));
        assert!(rendered.contains("pub fn show_pet_by_id"), "{rendered}");
        assert!(
            rendered.contains("pub struct ShowPetById<'a>"),
            "{rendered}"
        );
        // The separator, the literal segment, the separator, the variable.
        assert!(rendered.contains(r"url.push('/')"), "{rendered}");
        assert!(rendered.contains(r#"url.push_str("pets")"#), "{rendered}");
        assert!(
            rendered.contains("support::style::path_segment"),
            "{rendered}"
        );
        // A required parameter is an ordinary setter and a check at `send`, which is what
        // "runtime-checked rather than typestate" means in the output.
        assert!(rendered.contains("support::Unset::new"), "{rendered}");
    }

    #[test]
    fn a_named_type_is_qualified_wherever_it_is_not_the_types_module() {
        // A schema called `Error`: unqualified, this renders `Error<Error>` whose two `Error`s are
        // different types — the support module's and this one — and it compiles.
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {
                    "200": {"description": "ok", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Pet"}}}},
                    "404": {"description": "gone", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
                },
            }}},
            "components": {"schemas": {
                "Pet": {"type": "object", "properties": {"name": {"type": "string"}}},
                "Error": {"type": "object", "properties": {"message": {"type": "string"}}},
            }},
        }));
        assert!(
            rendered.contains("ResponseValue<super::types::Pet>"),
            "{rendered}"
        );
        assert!(
            rendered.contains("Error<super::types::Error>"),
            "{rendered}"
        );
    }

    #[test]
    fn several_declared_failures_become_an_enum_and_one_does_not() {
        let two = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {
                    "200": {"description": "ok"},
                    "404": {"description": "gone"},
                    "429": {"description": "slow down", "content": {"application/json": {"schema": {"type": "string"}}}},
                },
            }}},
        }));
        assert!(two.contains("pub enum ListPetsError"), "{two}");
        assert!(two.contains("NotFound(())"), "{two}");
        assert!(two.contains("TooManyRequests(String)"), "{two}");

        // One failure needs no enum: its payload type is the error type.
        let one = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {
                    "200": {"description": "ok"},
                    "404": {"description": "gone", "content": {"application/json": {"schema": {"type": "string"}}}},
                },
            }}},
        }));
        assert!(!one.contains("pub enum ListPetsError"), "{one}");
        assert!(one.contains("Error<String>"), "{one}");
    }

    /// One operation with one request body of the given media type and schema.
    fn body_client(media_type: &str, entry: &Value) -> String {
        client(json!({
            "openapi": "3.1.0",
            "paths": {"/upload": {"post": {
                "operationId": "upload",
                "requestBody": {"required": true, "content": {media_type: entry}},
                "responses": {"200": {"description": "ok"}},
            }}},
        }))
    }

    #[test]
    fn a_form_body_is_encoded_by_the_style_table_rather_than_as_json() {
        let rendered = body_client(
            "application/x-www-form-urlencoded",
            &json!({"schema": {"type": "object", "properties": {"grant_type": {"type": "string"}}}}),
        );
        assert!(
            rendered.contains("application/x-www-form-urlencoded"),
            "{rendered}"
        );
        assert!(
            rendered.contains("support::style::form_body("),
            "{rendered}"
        );
        // The body is still the typed struct: a form body differs from a JSON one in how it is
        // written, not in what the caller builds.
        assert!(!rendered.contains("request.json(body)"), "{rendered}");
    }

    #[test]
    fn a_form_bodys_encoding_reaches_the_generated_table() {
        let rendered = body_client(
            "application/x-www-form-urlencoded",
            &json!({
                "schema": {"type": "object", "properties": {"tag": {"type": "array", "items": {"type": "string"}}}},
                "encoding": {"tag": {"style": "spaceDelimited", "explode": false}},
            }),
        );
        assert!(
            rendered.contains("support::style::FormSpec"),
            "the encoding declaration did not reach the emitted table: {rendered}"
        );
        assert!(
            rendered.contains("support::style::Style::SpaceDelimited"),
            "{rendered}"
        );
        assert!(rendered.contains("explode: false"), "{rendered}");
    }

    #[test]
    fn a_multipart_bodys_parts_come_from_the_contract() {
        let rendered = body_client(
            "multipart/form-data",
            &json!({"schema": {"type": "object", "properties": {
                "file": {"type": "string", "format": "binary"},
                "name": {"type": "string"},
                "tags": {"type": "array", "items": {"type": "string"}},
            }}}),
        );
        assert!(rendered.contains("support::multipart::body("), "{rendered}");
        // One row per member, each classified from the type the member was actually given.
        assert!(
            rendered.contains("name: \"file\"") && rendered.contains("PartKind::File"),
            "{rendered}"
        );
        assert!(
            rendered.contains("name: \"name\"") && rendered.contains("PartKind::Text"),
            "{rendered}"
        );
        // An array is the item's kind, repeated — 3.1's rule. 3.0 would have said one JSON array
        // here, which is not what a server parsing repeated fields is looking for.
        assert!(
            rendered.contains("name: \"tags\"") && rendered.contains("repeated: true"),
            "{rendered}"
        );
        assert_eq!(rendered.matches("PartKind::Text").count(), 2, "{rendered}");
        // The boundary is chosen from the content, so the header cannot be set before the body
        // exists — which is why both come back from one call.
        assert!(rendered.contains("let (content_type, bytes)"), "{rendered}");
    }

    #[test]
    fn a_multipart_encoding_names_a_parts_content_type() {
        let rendered = body_client(
            "multipart/form-data",
            &json!({
                "schema": {"type": "object", "properties": {"metadata": {"type": "object"}}},
                "encoding": {"metadata": {"contentType": "application/json"}},
            }),
        );
        assert!(
            rendered.contains("content_type: ::std::option::Option::Some(\"application/json\")"),
            "{rendered}"
        );
    }

    #[test]
    fn a_content_type_listing_several_alternatives_is_not_an_instruction() {
        // `cloudflare` writes ten comma-separated types on one part. That is the set a server
        // accepts, not a decision about what to send, and sending the whole string as one header
        // would be sending a content type that is not one.
        let rendered = body_client(
            "multipart/form-data",
            &json!({
                "schema": {"type": "object", "properties": {"module": {"type": "string", "format": "binary"}}},
                "encoding": {"module": {"contentType": "text/javascript, application/wasm, text/plain"}},
            }),
        );
        assert!(!rendered.contains("application/wasm"), "{rendered}");
        assert!(
            rendered.contains("content_type: ::std::option::Option::None"),
            "{rendered}"
        );
    }

    #[test]
    fn a_text_body_is_a_string_and_a_binary_one_is_bytes() {
        let text = body_client("text/plain", &json!({"schema": {"type": "string"}}));
        assert!(text.contains("::std::string::String"), "{text}");
        assert!(text.contains("\"text/plain\""), "{text}");

        let binary = body_client(
            "application/octet-stream",
            &json!({"schema": {"type": "string", "format": "binary"}}),
        );
        assert!(binary.contains("::std::vec::Vec<u8>"), "{binary}");
    }

    #[test]
    fn a_body_that_declares_only_a_wildcard_sends_something_a_server_can_read() {
        // `preference` sorts a wildcard last, which decides nothing when it is the only entry.
        // `Content-Type: */*` is not a content type, and 9 corpus bodies declare exactly that.
        let binary = body_client(
            "image/*",
            &json!({"schema": {"type": "string", "format": "binary"}}),
        );
        assert!(!binary.contains("\"image/*\""), "{binary}");
        assert!(binary.contains("application/octet-stream"), "{binary}");
        assert!(binary.contains("::std::vec::Vec<u8>"), "{binary}");
    }

    #[test]
    fn a_wildcard_over_a_real_schema_keeps_the_type_the_document_gave() {
        // `telnyx` writes `*/*` over a `$ref` to an object. A wildcard permits every content type,
        // so choosing bytes there would throw away a type the document supplied for no reason —
        // JSON is the one content type the declared schema actually fits.
        let rendered = body_client(
            "*/*",
            &json!({"schema": {"type": "object", "properties": {"start": {"type": "string"}}}}),
        );
        assert!(rendered.contains("request.json(body)"), "{rendered}");
        assert!(!rendered.contains("Vec<u8>"), "{rendered}");
    }

    #[test]
    fn a_default_that_claims_success_is_still_a_failure_variant() {
        // `weather-gov` writes a `302` and a `default` and no `2XX`, so the `default` is both the
        // success arm and the catch-all failure. Two answers about that used to disagree: the error
        // type counted two failure arms and declared an enum, while `send` counted one and decoded
        // the body straight into it — asking an enum that derives only `Debug, Clone` to
        // deserialize. The client did not compile, and no document in the quick tier had the shape.
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/briefing": {"get": {
                "operationId": "getBriefing",
                "responses": {
                    "302": {"description": "found"},
                    "default": {"description": "problem", "content": {"application/json": {"schema": {"type": "string"}}}},
                },
            }}},
        }));
        assert!(rendered.contains("pub enum GetBriefingError"), "{rendered}");
        // Every failure path puts the body in a variant rather than handing the enum to serde.
        assert!(
            rendered.contains("GetBriefingError::Status302"),
            "{rendered}"
        );
        assert!(rendered.contains("GetBriefingError::Default"), "{rendered}");
    }

    #[test]
    fn a_deprecated_operation_does_not_warn_in_the_consumers_crate() {
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/artists": {"get": {
                "operationId": "getArtists",
                "deprecated": true,
                "responses": {"200": {"description": "ok"}},
            }}},
        }));
        assert!(rendered.contains("#[deprecated]"), "{rendered}");
        // The builder is deprecated, so its own `impl` block uses a deprecated type — a warning
        // about code the consumer did not write. An `impl` cannot be deprecated, so it says the
        // only thing that distinguishes "this is the deprecated thing" from "this uses one".
        assert!(
            rendered.contains("#[allow(deprecated)]\nimpl<'a> GetArtists<'a>"),
            "{rendered}"
        );

        // The accessor is the same problem one level up: it is `#[deprecated]` itself, and it both
        // returns the deprecated builder and constructs one. Carrying the attribute exempts it from
        // nothing — rustc lints the signature and the body — so it needs the allowance too.
        assert!(
            rendered.contains("#[allow(deprecated)]\n    #[must_use]\n    pub fn get_artists"),
            "{rendered}"
        );

        // And an operation the document does not deprecate carries neither.
        let plain = client(json!({
            "openapi": "3.1.0",
            "paths": {"/artists": {"get": {"operationId": "getArtists", "responses": {"200": {"description": "ok"}}}}},
        }));
        assert!(!plain.contains("deprecated"), "{plain}");
    }

    #[test]
    fn a_type_that_names_a_deprecated_type_does_not_warn_in_the_consumers_crate() {
        // `okta` deprecates the `MtlsTrustCredentialsRevocation` component and not the `revocation`
        // property that holds one. Both renderings are faithful — and rustc lints the use anyway,
        // so the generated crate warned on every build about code its consumer did not write.
        let rendered = types(
            with_schemas(json!({
                "Retired": {"type": "string", "enum": ["a", "b"], "deprecated": true},
                "Holder": {
                    "type": "object",
                    "properties": {"revocation": {"$ref": "#/components/schemas/Retired"}},
                },
            })),
            &Config::default(),
        );
        // On the item, not the field: a field-level allowance does not reach the `Deserialize` the
        // derive expands from it, which names the same type at the same span.
        let declaration = rendered
            .split_once("pub struct Holder")
            .map(|(before, _)| before)
            .expect("the holder should be rendered");
        assert!(declaration.contains("#[allow(deprecated)]"), "{rendered}");

        // A holder of something the document did not deprecate carries nothing.
        let plain = types(
            with_schemas(json!({
                "Live": {"type": "string", "enum": ["a", "b"]},
                "Holder": {
                    "type": "object",
                    "properties": {"revocation": {"$ref": "#/components/schemas/Live"}},
                },
            })),
            &Config::default(),
        );
        assert!(!plain.contains("allow(deprecated)"), "{plain}");
    }

    #[test]
    fn an_operation_whose_only_response_is_default_still_has_a_success_path() {
        // `default` means "anything not otherwise claimed". With no `2XX` beside it, a `200` is
        // exactly that — so treating the arm as a failure would report every successful call as
        // one, which is what the first implementation did.
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {"default": {
                    "description": "whatever happens",
                    "content": {"application/json": {"schema": {"type": "string"}}},
                }},
            }}},
        }));
        assert!(
            rendered.contains("ResponseValue<String>, Error<String>"),
            "{rendered}"
        );
        assert!(
            rendered.contains("200..=299 => ::std::result::Result::Ok"),
            "{rendered}"
        );

        // With a declared success beside it, `default` goes back to being the failure it claims.
        let with_success = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {
                    "200": {"description": "ok"},
                    "default": {"description": "anything else", "content": {"application/json": {"schema": {"type": "string"}}}},
                },
            }}},
        }));
        assert!(
            !with_success.contains("200..=299 => ::std::result::Result::Ok"),
            "{with_success}"
        );
        assert!(
            with_success.contains("ResponseValue<()>, Error<String>"),
            "{with_success}"
        );
    }

    #[test]
    fn only_a_server_url_a_client_could_actually_use_becomes_a_default() {
        let with_server = |servers: Value| {
            let mut document = json!({
                "openapi": "3.1.0",
                "paths": {"/pets": {"get": {"operationId": "listPets", "responses": {"200": {"description": "ok"}}}}},
            });
            document
                .as_object_mut()
                .unwrap()
                .insert("servers".to_owned(), servers);
            client(document)
        };

        let absolute = with_server(json!([{"url": "https://example.invalid/v1"}]));
        assert!(
            absolute.contains("impl ::std::default::Default"),
            "{absolute}"
        );
        assert!(
            absolute.contains("https://example.invalid/v1"),
            "{absolute}"
        );

        // A relative URL is what the description is served next to, and only the caller knows what
        // that was; a templated one has variables progeny does not substitute. Both are perfectly
        // good things for a document to say and neither is a default a client could send to.
        for servers in [
            json!([{"url": "/api/v3"}]),
            json!([{"url": "https://{region}.example.invalid"}]),
        ] {
            let rendered = with_server(servers);
            assert!(
                !rendered.contains("impl ::std::default::Default"),
                "{rendered}"
            );
        }
    }

    #[test]
    fn an_undeclared_status_is_handed_back_raw_rather_than_given_a_shape() {
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {"200": {"description": "ok"}},
            }}},
        }));
        assert!(
            rendered.contains("Error::UnexpectedStatus(response)"),
            "{rendered}"
        );

        // …unless the document declares a `default` arm, which is exactly what claims the rest.
        let with_default = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "responses": {
                    "200": {"description": "ok"},
                    "default": {"description": "anything else"},
                },
            }}},
        }));
        assert!(
            !with_default.contains("Error::UnexpectedStatus(response)"),
            "{with_default}"
        );
    }

    #[test]
    fn a_query_parameter_carries_the_style_the_document_asked_for() {
        let rendered = client(json!({
            "openapi": "3.1.0",
            "paths": {"/pets": {"get": {
                "operationId": "listPets",
                "parameters": [
                    {"name": "tags", "in": "query", "style": "pipeDelimited", "explode": false,
                     "schema": {"type": "array", "items": {"type": "string"}}},
                    {"name": "x-trace", "in": "header", "schema": {"type": "string"}},
                ],
                "responses": {"200": {"description": "ok"}},
            }}},
        }));
        assert!(
            rendered.contains("support::style::Style::PipeDelimited"),
            "{rendered}"
        );
        assert!(
            rendered.contains("support::style::query_pairs("),
            "{rendered}"
        );
        assert!(rendered.contains(r#""tags""#), "{rendered}");
        assert!(
            rendered.contains(r#".header("x-trace", support::style::header_value"#),
            "{rendered}"
        );
    }

    #[test]
    fn generation_is_deterministic() {
        let document = with_schemas(json!({
            "A": {"type": "object", "properties": {"b": {"$ref": "#/components/schemas/B"}}},
            "B": {"type": "object", "properties": {"a": {"$ref": "#/components/schemas/A"}}},
        }));
        let once = types(document.clone(), &Config::default());
        let twice = types(document, &Config::default());
        assert_eq!(once, twice);
    }
}
