//! Rendering: pure functions from frozen contracts to source text.
//!
//! Two packagings of one rendering. **Crate mode** writes a manifest and a `src` tree; **module
//! mode** writes the same modules nested into a single file, for `include!` from a build script or
//! for checking in. One renderer, two wrappers, no forked logic — so a change to how a type is
//! written cannot land in one packaging and not the other.
//!
//! **Determinism is an output invariant**: the same document, configuration and progeny version
//! render byte-identical source. Everything here iterates `BTreeMap`s and `Vec`s in a fixed order,
//! and the corpus harness generates every document twice per run and compares.

mod manifest;
mod serde_impl;
mod types;

use std::collections::BTreeMap;

use camino::Utf8PathBuf;
use proc_macro2::TokenStream;
use quote::quote;

use crate::config::{Config, Packaging};
use crate::contract::Contracts;

/// Render the contracts into the files a caller writes out.
pub(crate) fn run(contracts: &Contracts, config: &Config) -> BTreeMap<Utf8PathBuf, String> {
    let mut files = BTreeMap::new();
    if !config.emit.types {
        return files;
    }
    let mut body = types::render(contracts, config);
    body.extend(serde_impl::render(contracts, config));
    let mut modules = vec![("types", body)];
    // Emitted only when something calls into it: an unused module is compile time the consumer did
    // not ask for.
    if serde_impl::needed(contracts) {
        modules.push(("support", crate::support::tokens()));
    }

    match config.packaging {
        Packaging::Crate => {
            files.insert(
                Utf8PathBuf::from("Cargo.toml"),
                manifest::render(contracts, config),
            );
            let declarations = modules.iter().map(|(name, _)| {
                let ident = quote::format_ident!("{name}");
                // The support module is not part of the generated crate's public API; it is
                // reachable because the type modules call into it and for no other reason.
                let hidden = (*name == "support").then(|| quote! { #[doc(hidden)] });
                quote! { #hidden pub mod #ident; }
            });
            files.insert(
                Utf8PathBuf::from("src/lib.rs"),
                source(&quote! {
                    #![doc = " Generated by progeny. Edits are overwritten on the next run."]
                    #(#declarations)*
                }),
            );
            for (name, tokens) in modules {
                files.insert(Utf8PathBuf::from(format!("src/{name}.rs")), source(&tokens));
            }
        }
        Packaging::Module => {
            let nested = modules.into_iter().map(|(name, tokens)| {
                let ident = quote::format_ident!("{name}");
                let hidden = (name == "support").then(|| quote! { #[doc(hidden)] });
                quote! { #hidden pub mod #ident { #tokens } }
            });
            files.insert(
                Utf8PathBuf::from("progeny.rs"),
                source(&quote! {
                    #![doc = " Generated by progeny. Edits are overwritten on the next run."]
                    #(#nested)*
                }),
            );
        }
    }
    files
}

/// Format a token stream as source text.
///
/// `prettyplease` rather than rustfmt: a formatter that runs in-process needs no toolchain at
/// generation time and cannot be missing. A stream that does not parse as a file falls back to the
/// token text, which is still valid Rust and still compiles — a formatting failure must not be able
/// to fail a build.
fn source(tokens: &TokenStream) -> String {
    match syn::parse2::<syn::File>(tokens.clone()) {
        Ok(file) => prettyplease::unparse(&file),
        Err(_) => tokens.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use serde_json::{Value, json};

    use crate::config::{Config, Packaging, SerdeImpl};
    use crate::diag::Ctx;
    use crate::doc::parse as doc_parse;
    use crate::{contract, normalize, resolve, shape};

    /// Generate the types module for a document.
    fn types(document: Value, config: &Config) -> String {
        let mut ctx = Ctx::new();
        let normalized = normalize::normalize(document, &mut ctx).unwrap();
        let parsed = doc_parse::document(normalized, &mut ctx);
        let resolved = resolve::resolve(parsed, &mut ctx);
        let shapes = shape::classify(&resolved, &mut ctx);
        let contracts = contract::build(&resolved, &shapes, config, &mut ctx).unwrap();
        let files = super::run(&contracts, config);
        files
            .get(camino::Utf8Path::new("src/types.rs"))
            .cloned()
            .unwrap_or_default()
    }

    fn with_schemas(schemas: Value) -> Value {
        // Built member by member rather than with `json!`, which would only borrow `schemas`.
        let mut components = serde_json::Map::new();
        components.insert("schemas".to_owned(), schemas);
        let mut root = serde_json::Map::new();
        root.insert("openapi".to_owned(), Value::String("3.1.0".to_owned()));
        root.insert("paths".to_owned(), Value::Object(serde_json::Map::new()));
        root.insert("components".to_owned(), Value::Object(components));
        Value::Object(root)
    }

    #[test]
    fn a_struct_renders_with_its_wire_names_and_its_docs() {
        let rendered = types(
            with_schemas(json!({
                "Pet": {
                    "type": "object",
                    "description": "One pet.",
                    "required": ["petName"],
                    "properties": {
                        "petName": {"type": "string", "description": "What it answers to."},
                        "type": {"type": "string"},
                        "tags": {"type": "array", "items": {"type": "string"}},
                    },
                },
            })),
            &Config::default(),
        );
        assert!(rendered.contains("pub struct Pet {"), "{rendered}");
        assert!(rendered.contains("/// One pet."), "{rendered}");
        assert!(rendered.contains("/// What it answers to."), "{rendered}");
        // Case conversion on the Rust side, the wire name kept exactly.
        assert!(
            rendered.contains(r#"#[serde(rename = "petName")]"#),
            "{rendered}"
        );
        assert!(rendered.contains("pub pet_name: String"), "{rendered}");
        // A reserved word is renamed with a suffix, and says what it was.
        assert!(rendered.contains(r#"rename = "type""#), "{rendered}");
        assert!(rendered.contains("pub type_: Option<String>"), "{rendered}");
        assert!(
            rendered.contains(r#"skip_serializing_if = "Option::is_none""#),
            "{rendered}"
        );
        assert!(
            rendered.contains("pub tags: Option<Vec<String>>"),
            "{rendered}"
        );
    }

    #[test]
    fn the_rendered_source_parses_as_rust() {
        // Formatting is what proves the stream is syntactically valid: `prettyplease` only runs on
        // a `syn::File`, and the fallback would leave the tokens on one line.
        let rendered = types(
            with_schemas(json!({
                "Pet": {"type": "object", "properties": {"name": {"type": "string"}}},
            })),
            &Config::default(),
        );
        syn::parse_file(&rendered).unwrap();
        assert!(rendered.lines().count() > 3, "{rendered}");
    }

    #[test]
    fn a_fieldless_enum_keeps_the_bytes_it_had() {
        let rendered = types(
            with_schemas(json!({
                "State": {"type": "string", "enum": ["in-progress", "done", "2fa"]},
            })),
            &Config::default(),
        );
        assert!(rendered.contains("pub enum State"), "{rendered}");
        assert!(
            rendered.contains(r#"#[serde(rename = "in-progress")]"#),
            "{rendered}"
        );
        assert!(rendered.contains("InProgress,"), "{rendered}");
        assert!(rendered.contains("_2fa,"), "{rendered}");
    }

    #[test]
    fn a_union_renders_untagged() {
        let rendered = types(
            with_schemas(json!({
                "Either": {"oneOf": [{"type": "string"}, {"type": "integer"}]},
            })),
            &Config::default(),
        );
        assert!(rendered.contains("#[serde(untagged)]"), "{rendered}");
        assert!(rendered.contains("Text(String)"), "{rendered}");
        assert!(rendered.contains("Integer(i64)"), "{rendered}");
    }

    #[test]
    fn a_default_is_rendered_as_a_value_rather_than_recorded_and_forgotten() {
        let rendered = types(
            with_schemas(json!({
                "Options": {
                    "type": "object",
                    "properties": {
                        "limit": {"type": "integer", "default": 20},
                        "name": {"type": "string", "default": "unnamed"},
                    },
                },
            })),
            &Config::default(),
        );
        assert!(
            rendered.contains(r#"default = "default_options_limit""#),
            "{rendered}"
        );
        assert!(
            rendered.contains("fn default_options_limit() -> Option<i64>"),
            "{rendered}"
        );
        assert!(rendered.contains("Some(20i64)"), "{rendered}");
        assert!(
            rendered.contains(r#"Some("unnamed".to_owned())"#),
            "{rendered}"
        );
    }

    #[test]
    fn the_hand_written_strategy_leaves_no_serde_attributes_behind() {
        // Attributes are helper attributes of the serde derive macros: with no derive on the item
        // they do not even resolve, so leaving one behind would not compile.
        let config = Config {
            serde_impl: SerdeImpl::HandWrittenWhereEligible,
            ..Config::default()
        };
        let rendered = types(
            with_schemas(json!({
                "Pet": {"type": "object", "properties": {"petName": {"type": "string"}}},
            })),
            &config,
        );
        assert!(!rendered.contains("#[serde("), "{rendered}");
        assert!(!rendered.contains("#[derive(serde::"), "{rendered}");
        assert!(
            rendered.contains("pub pet_name: Option<String>"),
            "{rendered}"
        );
        // Two function bodies per type, calling into the machinery that lives once per crate.
        assert!(
            rendered.contains("impl<'de> serde::Deserialize<'de> for Pet"),
            "{rendered}"
        );
        assert!(
            rendered.contains("impl serde::Serialize for Pet"),
            "{rendered}"
        );
        assert!(
            rendered.contains("super::support::BufferVisitor"),
            "{rendered}"
        );
    }

    #[test]
    fn crate_mode_and_module_mode_render_the_same_types() {
        let document = with_schemas(json!({
            "Pet": {"type": "object", "properties": {"name": {"type": "string"}}},
        }));
        let as_crate = types(document.clone(), &Config::default());
        let module = Config {
            packaging: Packaging::Module,
            ..Config::default()
        };
        let mut ctx = Ctx::new();
        let normalized = normalize::normalize(document, &mut ctx).unwrap();
        let parsed = doc_parse::document(normalized, &mut ctx);
        let resolved = resolve::resolve(parsed, &mut ctx);
        let shapes = shape::classify(&resolved, &mut ctx);
        let contracts = contract::build(&resolved, &shapes, &module, &mut ctx).unwrap();
        let files = super::run(&contracts, &module);
        assert_eq!(files.len(), 1);
        let nested = files
            .get(camino::Utf8Path::new("progeny.rs"))
            .cloned()
            .unwrap_or_default();
        assert!(nested.contains("pub mod types"), "{nested}");
        // The same struct, indented into a module: one renderer behind both packagings.
        assert!(nested.contains("pub struct Pet"), "{nested}");
        assert!(as_crate.contains("pub struct Pet"), "{as_crate}");
    }

    #[test]
    fn generation_is_deterministic() {
        let document = with_schemas(json!({
            "A": {"type": "object", "properties": {"b": {"$ref": "#/components/schemas/B"}}},
            "B": {"type": "object", "properties": {"a": {"$ref": "#/components/schemas/A"}}},
        }));
        let once = types(document.clone(), &Config::default());
        let twice = types(document, &Config::default());
        assert_eq!(once, twice);
    }
}
