//! The generated runtime-benchmark subject.
//!
//! Each subject is an ordinary generated types crate plus one small binary. The binary names every
//! payload type statically, measures deserialization inside the process, and reports allocator
//! counters that process RSS cannot distinguish from code and runtime overhead.

use std::fmt::Write as _;

use color_eyre::eyre::{self, WrapErr};
use serde_json::{Map, Value, json};

use super::Case;

pub(crate) const DEEP_DEPTH: usize = 24;
pub(crate) const DEEP_ITEMS: usize = 2_048;
const DEEP_VALUES: usize = 16;

pub(crate) struct DeepFixture {
    pub(crate) document: Vec<u8>,
    pub(crate) malformed: String,
    pub(crate) payload_bytes: usize,
}

/// A large body followed by a deeply nested tail.
///
/// The malformed value sits at the end of the tail. Object fields sort as `items`, then `tail`, so
/// reaching it requires reading the large array first and then walking the full depth.
pub(crate) fn deep_fixture() -> eyre::Result<DeepFixture> {
    let mut schemas = Map::new();
    schemas.insert(
        "RuntimeItem".to_owned(),
        json!({
            "type": "object",
            "required": ["id", "label", "values"],
            "properties": {
                "id": {"type": "integer"},
                "label": {"type": "string"},
                "values": {"type": "array", "items": {"type": "integer"}}
            }
        }),
    );
    schemas.insert(
        "RuntimeTailEnd".to_owned(),
        json!({
            "type": "object",
            "required": ["count"],
            "properties": {"count": {"type": "integer"}}
        }),
    );
    let mut next = "#/components/schemas/RuntimeTailEnd".to_owned();
    for depth in (0..DEEP_DEPTH).rev() {
        let name = format!("RuntimeTail{depth}");
        schemas.insert(
            name.clone(),
            json!({
                "type": "object",
                "required": ["next"],
                "properties": {"next": {"$ref": next}}
            }),
        );
        next = format!("#/components/schemas/{name}");
    }
    schemas.insert(
        "RuntimeEnvelope".to_owned(),
        json!({
            "type": "object",
            "required": ["items", "tail"],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {"$ref": "#/components/schemas/RuntimeItem"}
                },
                "tail": {"$ref": next}
            }
        }),
    );

    let label = "runtime payload ".repeat(4);
    let values: Vec<usize> = (0..DEEP_VALUES).collect();
    let items: Vec<Value> = (0..DEEP_ITEMS)
        .map(|id| {
            json!({
                "id": id,
                "label": label,
                "values": values
            })
        })
        .collect();
    let valid = json!({
        "items": items,
        "tail": nested_tail(&json!(7))
    });
    let malformed = json!({
        "items": valid.get("items").cloned().unwrap_or(Value::Null),
        "tail": nested_tail(&json!("not an integer"))
    });
    let payload_bytes = valid.to_string().len();
    let document = json!({
        "openapi": "3.1.0",
        "info": {"title": "runtime benchmark", "version": "1"},
        "paths": {
            "/runtime": {
                "get": {
                    "operationId": "runtime",
                    "responses": {
                        "200": {
                            "description": "runtime payload",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/RuntimeEnvelope"},
                                    "example": valid
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {"schemas": schemas}
    });
    Ok(DeepFixture {
        document: serde_json::to_vec(&document).wrap_err("rendering the deep runtime fixture")?,
        malformed: malformed.to_string(),
        payload_bytes,
    })
}

fn nested_tail(count: &Value) -> Value {
    let mut tail = json!({"count": count});
    for _ in 0..DEEP_DEPTH {
        tail = json!({"next": tail});
    }
    tail
}

pub(crate) fn render(
    package: &str,
    valid: &[Case],
    malformed: &[Case],
    iterations: usize,
) -> String {
    let krate = crate::corpus::lib_name(package);
    let mut out = indoc::formatdoc! {r"
        //! Generated by `cargo xtask bench-runtime`.
        #![deny(warnings)]

        use std::alloc::{{GlobalAlloc, Layout, System}};
        use std::hint::black_box;
        use std::sync::atomic::{{AtomicU64, Ordering}};
        use std::time::Instant;

        use {krate}::types;

        const ITERATIONS: usize = {iterations};

    "};
    out.push_str(RUNNER);
    out.push_str(indoc::indoc! {"

        fn valid_once() -> Result<(), serde_json::Error> {
    "});
    if valid.is_empty() {
        out.push_str(
            "    let _read: fn(&str) -> Result<(), serde_json::Error> = \
             read::<serde_json::Value>;\n",
        );
    }
    for case in valid {
        let _ = writeln!(
            out,
            "    read::<types::{}>({:?})?;",
            case.type_name, case.json
        );
    }
    out.push_str(indoc::indoc! {"
            Ok(())
        }

        fn malformed_once() -> usize {
    "});
    if malformed.is_empty() {
        out.push_str(
            "    let _reject: fn(&str) -> bool = reject::<serde_json::Value>;\n\
                 let rejected = 0usize;\n",
        );
    } else {
        out.push_str("    let mut rejected = 0usize;\n");
    }
    for case in malformed {
        let _ = writeln!(
            out,
            "    rejected += usize::from(reject::<types::{}>({:?}));",
            case.type_name, case.json
        );
    }
    out.push_str(indoc::indoc! {"
            rejected
        }

        fn malformed_outcomes() -> Vec<String> {
    "});
    if malformed.is_empty() {
        out.push_str(
            "    let _capture: fn(&mut Vec<String>, &str, &str) = \
             capture::<serde_json::Value>;\n\
                 let outcomes = Vec::new();\n",
        );
    } else {
        out.push_str("    let mut outcomes = Vec::new();\n");
    }
    for case in malformed {
        let _ = writeln!(
            out,
            "    capture::<types::{}>(&mut outcomes, {:?}, {:?});",
            case.type_name, case.label, case.json
        );
    }
    out.push_str(indoc::indoc! {"
            outcomes
        }
    "});
    out
}

const RUNNER: &str = indoc::indoc! {r#"
struct CountingAllocator;

#[global_allocator]
static ALLOCATOR: CountingAllocator = CountingAllocator;
static ALLOCATIONS: AtomicU64 = AtomicU64::new(0);
static LIVE_BYTES: AtomicU64 = AtomicU64::new(0);
static PEAK_BYTES: AtomicU64 = AtomicU64::new(0);

#[expect(
    unsafe_code,
    reason = "implementing GlobalAlloc necessarily calls the unsafe System allocator methods"
)]
unsafe impl GlobalAlloc for CountingAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let pointer = unsafe { System.alloc(layout) };
        if !pointer.is_null() {
            allocated(layout.size());
        }
        pointer
    }

    unsafe fn dealloc(&self, pointer: *mut u8, layout: Layout) {
        LIVE_BYTES.fetch_sub(bytes(layout.size()), Ordering::Relaxed);
        unsafe { System.dealloc(pointer, layout) };
    }

    unsafe fn realloc(&self, pointer: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        let replacement = unsafe { System.realloc(pointer, layout, new_size) };
        if !replacement.is_null() {
            ALLOCATIONS.fetch_add(1, Ordering::Relaxed);
            let old = bytes(layout.size());
            let new = bytes(new_size);
            let live = if new >= old {
                LIVE_BYTES.fetch_add(new - old, Ordering::Relaxed) + (new - old)
            } else {
                LIVE_BYTES.fetch_sub(old - new, Ordering::Relaxed) - (old - new)
            };
            update_peak(live);
        }
        replacement
    }
}

fn bytes(size: usize) -> u64 {
    u64::try_from(size).unwrap_or(u64::MAX)
}

fn allocated(size: usize) {
    ALLOCATIONS.fetch_add(1, Ordering::Relaxed);
    let live = LIVE_BYTES.fetch_add(bytes(size), Ordering::Relaxed) + bytes(size);
    update_peak(live);
}

fn update_peak(live: u64) {
    let mut peak = PEAK_BYTES.load(Ordering::Relaxed);
    while live > peak {
        match PEAK_BYTES.compare_exchange_weak(peak, live, Ordering::Relaxed, Ordering::Relaxed) {
            Ok(_) => break,
            Err(observed) => peak = observed,
        }
    }
}

fn reset_allocator() -> u64 {
    ALLOCATIONS.store(0, Ordering::Relaxed);
    let baseline = LIVE_BYTES.load(Ordering::Relaxed);
    PEAK_BYTES.store(baseline, Ordering::Relaxed);
    baseline
}

fn allocator_result(baseline: u64) -> (u64, u64) {
    (
        ALLOCATIONS.load(Ordering::Relaxed),
        PEAK_BYTES.load(Ordering::Relaxed).saturating_sub(baseline),
    )
}

#[derive(serde::Serialize)]
struct Phase {
    wall_nanos: u64,
    allocations: u64,
    peak_heap_bytes: u64,
}

#[derive(serde::Serialize)]
struct Report {
    valid: Phase,
    malformed: Phase,
    malformed_cases: usize,
    malformed_rejected: usize,
    malformed_outcomes: Vec<String>,
}

fn read<T>(input: &str) -> Result<(), serde_json::Error>
where
    T: serde::de::DeserializeOwned,
{
    let value: T = serde_json::from_str(black_box(input))?;
    black_box(value);
    Ok(())
}

fn reject<T>(input: &str) -> bool
where
    T: serde::de::DeserializeOwned,
{
    let result = serde_json::from_str::<T>(black_box(input));
    black_box(&result);
    result.is_err()
}

fn capture<T>(outcomes: &mut Vec<String>, label: &str, input: &str)
where
    T: serde::de::DeserializeOwned,
{
    match serde_json::from_str::<T>(input) {
        Ok(value) => {
            black_box(value);
            outcomes.push(format!("{label}: accepted"));
        }
        Err(error) => outcomes.push(format!("{label}: {error}")),
    }
}

fn measure_valid() -> Result<Phase, serde_json::Error> {
    valid_once()?;
    let baseline = reset_allocator();
    let started = Instant::now();
    for _ in 0..ITERATIONS {
        valid_once()?;
    }
    let wall_nanos = u64::try_from(started.elapsed().as_nanos()).unwrap_or(u64::MAX);
    let (allocations, peak_heap_bytes) = allocator_result(baseline);
    Ok(Phase {
        wall_nanos,
        allocations,
        peak_heap_bytes,
    })
}

fn measure_malformed() -> (Phase, usize) {
    let rejected = malformed_once();
    let baseline = reset_allocator();
    let started = Instant::now();
    for _ in 0..ITERATIONS {
        black_box(malformed_once());
    }
    let wall_nanos = u64::try_from(started.elapsed().as_nanos()).unwrap_or(u64::MAX);
    let (allocations, peak_heap_bytes) = allocator_result(baseline);
    (
        Phase {
            wall_nanos,
            allocations,
            peak_heap_bytes,
        },
        rejected,
    )
}

fn main() -> Result<(), serde_json::Error> {
    let valid = measure_valid()?;
    let (malformed, malformed_rejected) = measure_malformed();
    let malformed_outcomes = malformed_outcomes();
    let report = Report {
        valid,
        malformed,
        malformed_cases: malformed_outcomes.len(),
        malformed_rejected,
        malformed_outcomes,
    };
    println!("RUNTIME {}", serde_json::to_string(&report)?);
    Ok(())
}
"#};

#[cfg(test)]
mod tests {
    use color_eyre::eyre;

    use super::render;
    use crate::runtime::Case;

    #[test_util::test]
    fn the_subject_names_every_case_and_parses_as_rust() {
        let valid = Case {
            label: "valid".to_owned(),
            type_name: "Pet".to_owned(),
            json: r#"{"id":1}"#.to_owned(),
        };
        let malformed = Case {
            label: "malformed".to_owned(),
            type_name: "Pet".to_owned(),
            json: r#"{"id":"wrong"}"#.to_owned(),
        };
        let source = render("runtime-test", &[valid], &[malformed], 7);
        assert!(source.contains("const ITERATIONS: usize = 7;"));
        assert!(source.contains("read::<types::Pet>"));
        assert!(source.contains("capture::<types::Pet>"));
        syn::parse_file(&source)?;
    }
}
