//! The example crate: one description, both halves, talking to each other.
//!
//! Every other gate in this project checks one side of the wire. The corpus checks that a document
//! round-trips; the compile gate checks that the emitted source is Rust; the payload gate runs serde
//! against real bodies. **None of them sends a request.** Whether a generated `send()` builds the
//! URL, query string, headers and cookies the description asks for has been checked only by reading
//! the emitted source, which is exactly the kind of claim this project has already been wrong about
//! twice.
//!
//! So this generates the client *and* the server from one description, implements the server's
//! `Api` trait with a double that records what arrived, starts it on a real socket, and calls it
//! with the generated client. A disagreement between the two halves about any part of the request
//! line is a failing test rather than a thing somebody notices in production.
//!
//! Its subject is the committed `petstore-31`, which needs no network and whose `rejectionProbe`
//! operation carries a path parameter, a query parameter, a header, a cookie and a body at once.

use std::fmt::Write as _;
use std::process::Command;

use anyhow::{Context, Result, bail};
use clap::Args as ClapArgs;

#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Write the example crate and stop, without compiling or running it.
    #[arg(long)]
    generate_only: bool,
}

/// The document the example is built from: committed, tiny, and exercising all four locations.
const SUBJECT: &str = "petstore-31";

pub fn run(args: &Args) -> Result<()> {
    crate::generated::require_cargo()?;

    let specs = crate::corpus::load_manifest()?;
    let spec = specs
        .iter()
        .find(|spec| spec.name == SUBJECT)
        .with_context(|| format!("no corpus document named `{SUBJECT}`"))?;
    let path = crate::corpus::document_path(spec);
    let bytes = std::fs::read(&path).with_context(|| format!("reading {path}"))?;

    let config = crate::corpus::config_for(spec);
    let output = progeny::generate(&bytes, &config).context("generating the example crate")?;
    let directory = crate::generated::write("example-petstore", &output)?;

    // The example needs a runtime and a socket, which a generated crate has no business declaring:
    // it is the *consumer* who chooses those. Appended to the manifest here for the same reason the
    // scratch crates get an empty `[workspace]` table — the harness's needs are not the product's.
    let manifest = directory.join("Cargo.toml");
    let existing =
        std::fs::read_to_string(&manifest).with_context(|| format!("reading {manifest}"))?;
    std::fs::write(
        &manifest,
        format!(
            "{existing}\n[dev-dependencies]\n\
             tokio = {{ version = \"1\", features = [\"rt-multi-thread\", \"macros\", \"net\"] }}\n"
        ),
    )
    .with_context(|| format!("writing {manifest}"))?;

    let tests = directory.join("tests");
    std::fs::create_dir_all(&tests).with_context(|| format!("creating {tests}"))?;
    let file = tests.join("both_halves.rs");
    std::fs::write(&file, test_source(&config.package.name))
        .with_context(|| format!("writing {file}"))?;

    println!("example: {SUBJECT}, both halves, at {directory}");
    if args.generate_only {
        println!("  written but not run: {file}");
        return Ok(());
    }

    let run = Command::new("cargo")
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", crate::generated::shared_target())
        .env_remove("RUSTFLAGS")
        .args([
            "test",
            "--quiet",
            "--all-features",
            "--test",
            "both_halves",
            "--",
            "--nocapture",
        ])
        .output()
        .context("running the example test")?;
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&run.stdout),
        String::from_utf8_lossy(&run.stderr)
    );
    if !run.status.success() {
        bail!("the generated client and server did not agree:\n{text}");
    }
    println!("{}", text.trim());
    println!();
    println!("example: the generated client and the generated server agree on the request line");
    Ok(())
}

/// The test that goes into the example crate.
///
/// Written out as source rather than assembled from the model on purpose: it is the *reader's*
/// check on progeny, and a test generated from the same records it is testing would agree with a
/// mistake in them. This one says what a petstore request looks like in plain Rust, and it is wrong
/// exactly when progeny is.
fn test_source(krate: &str) -> String {
    let krate = krate.replace('-', "_");
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Generated by `cargo xtask example`. The client and the server of one description,\n\
         //! talking over a real socket.\n\
         //!\n\
         //! This is the only assertion in the project that a generated `send()` builds the request\n\
         //! the description asks for: every other gate checks one side of the wire.\n"
    );
    let _ = writeln!(
        out,
        "use std::sync::{{Arc, Mutex}};\n\n\
         use {krate}::{{client, server, types}};\n"
    );
    out.push_str(RECORDER);
    out.push_str(IMPLEMENTATION);
    out.push_str(TESTS);
    out
}

/// The test double: an `Api` implementation that records what each handler was handed.
const RECORDER: &str = r#"
/// What the server saw, so the test can assert on the request rather than only on the reply.
/// Field-by-field rather than holding a `types::Pet`: a generated type carries only the derives
/// the configuration asked for, and `PartialEq` is not one of them by default. Comparing what the
/// server saw against what the client sent is the point, and it does not need the type to be
/// comparable.
#[derive(Debug, Default, Clone, PartialEq)]
struct Seen {
    limit: Option<i64>,
    pet_id: Option<String>,
    probe_id: Option<i64>,
    probe_limit: Option<i64>,
    probe_mode: Option<String>,
    probe_session: Option<i64>,
    probe_body: Option<(i64, String)>,
    photo_note: Option<String>,
    photo_file: Option<String>,
}

/// Cloneable rather than shared behind an `Arc` from outside, because `router` takes the
/// implementation by value and a foreign trait cannot be implemented for `Arc<T>` here anyway.
#[derive(Debug, Default, Clone)]
struct Double {
    seen: Arc<Mutex<Seen>>,
}

impl Double {
    fn record(&self, edit: impl FnOnce(&mut Seen)) {
        edit(&mut self.seen.lock().expect("the recorder is never poisoned"));
    }

    fn seen(&self) -> Seen {
        self.seen.lock().expect("the recorder is never poisoned").clone()
    }
}
"#;

/// The `Api` implementation. Spelled out rather than generated, so it reads as a consumer's would.
const IMPLEMENTATION: &str = r#"
impl server::Api for Double {
    async fn list_pets(&self, query: server::ListPetsQuery) -> server::ListPetsResponse {
        self.record(|seen| seen.limit = query.limit);
        server::ListPetsResponse::Ok(vec![types::Pet {
            id: 1,
            name: "Rex".to_owned(),
            tag: Some("dog".to_owned()),
        }])
    }

    async fn create_pets(&self) -> server::CreatePetsResponse {
        server::CreatePetsResponse::Created(())
    }

    async fn show_pet_by_id(&self, path: server::ShowPetByIdPath) -> server::ShowPetByIdResponse {
        self.record(|seen| seen.pet_id = Some(path.pet_id.clone()));
        server::ShowPetByIdResponse::Ok(types::Pet {
            id: 7,
            name: path.pet_id,
            tag: None,
        })
    }

    async fn upload_pet_photo(
        &self,
        path: server::UploadPetPhotoPath,
        body: types::UploadPetPhotoBody,
    ) -> server::UploadPetPhotoResponse {
        self.record(|seen| {
            seen.photo_note = body.note.clone();
            seen.photo_file = Some(body.file.clone());
        });
        server::UploadPetPhotoResponse::Created(types::PhotoUpload {
            pet_id: path.pet_id,
            filename: "photo".to_owned(),
            content_type: "image/png".to_owned(),
            file_size: body.file.len() as i64,
            note: body.note.unwrap_or_default(),
            rating: body.rating,
        })
    }

    async fn typed_errors(&self, path: server::TypedErrorsPath) -> server::TypedErrorsResponse {
        match path.kind.as_str() {
            "missing" => server::TypedErrorsResponse::NotFound(types::Error {
                code: 404,
                message: "missing".to_owned(),
            }),
            "conflict" => server::TypedErrorsResponse::Conflict(types::Error {
                code: 409,
                message: "conflict".to_owned(),
            }),
            _ => server::TypedErrorsResponse::NoContent(()),
        }
    }

    async fn rejection_probe(
        &self,
        path: server::RejectionProbePath,
        query: server::RejectionProbeQuery,
        header: server::RejectionProbeHeader,
        cookie: server::RejectionProbeCookie,
        body: types::Pet,
    ) -> server::RejectionProbeResponse {
        self.record(|seen| {
            seen.probe_id = Some(path.id);
            seen.probe_limit = Some(query.limit);
            seen.probe_mode = Some(header.x_mode.clone());
            seen.probe_session = Some(cookie.session);
            seen.probe_body = Some((body.id, body.name.clone()));
        });
        server::RejectionProbeResponse::NoContent(())
    }
}
"#;

/// The assertions themselves.
const TESTS: &str = r#"
/// Start the generated server on an ephemeral port and hand back a client pointed at it.
async fn serving() -> (Double, client::Client) {
    let double = Double::default();
    let router = server::router(double.clone());
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .expect("an ephemeral port");
    let address = listener.local_addr().expect("a bound address");
    tokio::spawn(async move {
        let _ = axum::serve(listener, router).await;
    });
    (double, client::Client::new(format!("http://{address}")))
}

#[tokio::test]
async fn a_query_parameter_survives_the_round_trip() {
    let (double, client) = serving().await;
    let pets = client.list_pets().limit(3i64).send().await.expect("a reply");
    assert_eq!(double.seen().limit, Some(3));
    assert_eq!(pets.into_value()[0].name, "Rex");

    // And an unset optional parameter arrives unset, rather than as a default the caller never
    // chose — the same rule the client's builder and the server's extractor have to agree on.
    let (double, client) = serving().await;
    let _ = client.list_pets().send().await.expect("a reply");
    assert_eq!(double.seen().limit, None);
}

#[tokio::test]
async fn a_path_parameter_survives_the_round_trip() {
    let (double, client) = serving().await;
    let pet = client
        .show_pet_by_id()
        .pet_id("a pet/with slashes")
        .send()
        .await
        .expect("a reply");
    // Percent-encoded on the way out and decoded on the way in, which is the pair of rules a
    // template variable actually depends on.
    assert_eq!(double.seen().pet_id.as_deref(), Some("a pet/with slashes"));
    assert_eq!(pet.into_value().name, "a pet/with slashes");
}

#[tokio::test]
async fn every_parameter_location_arrives_at_once() {
    // The one operation with a path parameter, a query parameter, a header, a cookie and a body
    // together. Four locations is where a renderer that puts one in the wrong place still passes
    // every other gate.
    let (double, client) = serving().await;
    let sent = types::Pet {
        id: 42,
        name: "Probe".to_owned(),
        tag: None,
    };
    let expected = (sent.id, sent.name.clone());
    client
        .rejection_probe()
        .id(9i64)
        .limit(11i64)
        .x_mode("strict")
        .session(1234i64)
        .body(sent)
        .send()
        .await
        .expect("a reply");
    let seen = double.seen();
    assert_eq!(seen.probe_id, Some(9));
    assert_eq!(seen.probe_limit, Some(11));
    assert_eq!(seen.probe_mode.as_deref(), Some("strict"));
    assert_eq!(seen.probe_session, Some(1234));
    assert_eq!(seen.probe_body, Some(expected));
}

#[tokio::test]
async fn a_multipart_body_survives_the_round_trip() {
    // The writer and the reader are the same rule read from two ends, and this is the only place
    // both ends actually run.
    let (double, client) = serving().await;
    let reply = client
        .upload_pet_photo()
        .pet_id(5i64)
        .body(types::UploadPetPhotoBody {
            file: "not really a png".to_owned(),
            note: Some("a note".to_owned()),
            rating: Some(4),
        })
        .send()
        .await
        .expect("a reply");
    let seen = double.seen();
    assert_eq!(seen.photo_file.as_deref(), Some("not really a png"));
    assert_eq!(seen.photo_note.as_deref(), Some("a note"));
    assert_eq!(reply.into_value().pet_id, 5);
}

#[tokio::test]
async fn a_declared_error_status_arrives_as_the_typed_error_it_was_sent_as() {
    // The client's status match and the server's response enum come from one record, and this is
    // the assertion that they agree about which arm a status lands in.
    let (_, client) = serving().await;
    let error = client
        .typed_errors()
        .kind("conflict")
        .send()
        .await
        .expect_err("a declared failure");
    let message = format!("{error:?}");
    assert!(message.contains("409"), "{message}");
    assert!(message.contains("conflict"), "{message}");

    let (_, client) = serving().await;
    client
        .typed_errors()
        .kind("neither")
        .send()
        .await
        .expect("the 204 arm");
}

#[tokio::test]
async fn a_request_the_description_does_not_describe_is_rejected_in_one_place() {
    // Not sent through the generated client, because the generated client cannot build a request
    // this wrong — which is the point of the builder. The rejection envelope exists for every
    // *other* client, and this is what it answers with.
    let (_, client) = serving().await;
    let raw = reqwest::Client::new();
    let response = raw
        .post(format!("{}/rejection-probe/9?limit=11", client.base_url()))
        .header("x-mode", "strict")
        .json(&types::Pet { id: 1, name: "p".to_owned(), tag: None })
        .send()
        .await
        .expect("a reply");
    assert_eq!(response.status(), 400);
    let body: serde_json::Value = response.json().await.expect("a JSON body");
    let message = body["message"].as_str().unwrap_or_default();
    assert!(message.contains("session"), "{body}");
    assert!(message.contains("rejection_probe"), "{body}");
}
"#;
