//! The example crate: one description, both halves, talking to each other.
//!
//! Every other gate in this project checks one side of the wire. The corpus checks that a document
//! round-trips; the compile gate checks that the emitted source is Rust; the payload gate runs serde
//! against real bodies. **None of them sends a request.** Whether a generated `send()` builds the
//! URL, query string, headers and cookies the description asks for has been checked only by reading
//! the emitted source, which is exactly the kind of claim this project has already been wrong about
//! twice.
//!
//! So this generates the client *and* the server from one description, implements the server's
//! `Api` trait with a double that records what arrived, starts it on a real socket, and calls it
//! with the generated client. A disagreement between the two halves about any part of the request
//! line is a failing test rather than a thing somebody notices in production.
//!
//! Its subject is the committed `petstore-31`, which needs no network and whose `rejectionProbe`
//! operation carries a path parameter, a query parameter, a header, a cookie and a body at once.

use std::fmt::Write as _;

use clap::Args as ClapArgs;
use color_eyre::eyre::{self, ContextCompat, WrapErr, bail};

#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Write the example crate and stop, without compiling or running it.
    #[arg(long)]
    generate_only: bool,

    /// Which serde strategy to generate with, rather than the configuration default.
    #[arg(long, value_name = "STRATEGY")]
    serde: Option<crate::corpus::SerdeChoice>,
}

/// The document the example is built from: committed, tiny, and exercising all four locations.
const SUBJECT: &str = "petstore-31";

pub fn run(args: &Args) -> eyre::Result<()> {
    crate::generated::require_cargo()?;

    let documents = crate::corpus::selected(&[SUBJECT.to_owned()])?;
    let (spec, bytes) = documents
        .first()
        .wrap_err("the subject resolves to itself")?;

    let mut config = crate::corpus::config_for(spec);
    if let Some(choice) = args.serde {
        config.serde_impl = choice.into();
    }
    // The paged listing, declared the way a consumer would declare it.
    config.pagination.insert(
        "list_pets_paged".to_owned(),
        progeny::Pagination {
            cursor_param: "cursor".to_owned(),
            next_cursor: "next".to_owned(),
            items: "items".to_owned(),
        },
    );
    let output = progeny::generate(bytes, &config).wrap_err("generating the example crate")?;
    let directory = crate::generated::write("example-petstore", &output)?;

    crate::generated::write_wire_test(
        &directory,
        "both_halves.rs",
        &test_source(&config.package.name),
    )?;

    println!("example: {SUBJECT}, both halves, at {directory}");
    if args.generate_only {
        println!("  written but not run: {directory}/tests/both_halves.rs");
        return Ok(());
    }

    let run = crate::generated::cargo(&directory)
        .args([
            "test",
            "--quiet",
            "--all-features",
            "--test",
            "both_halves",
            "--",
            "--nocapture",
        ])
        .output()
        .wrap_err("running the example test")?;
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&run.stdout),
        String::from_utf8_lossy(&run.stderr)
    );
    if !run.status.success() {
        bail!(
            "{}",
            indoc::formatdoc! {"
                the generated client and server did not agree:
                {text}"
            }
        );
    }
    println!("{}", text.trim());
    println!();
    println!("example: the generated client and the generated server agree on the request line");
    Ok(())
}

/// The test that goes into the example crate.
///
/// Written out as source rather than assembled from the model on purpose: it is the *reader's*
/// check on progeny, and a test generated from the same records it is testing would agree with a
/// mistake in them. This one says what a petstore request looks like in plain Rust, and it is wrong
/// exactly when progeny is.
fn test_source(krate: &str) -> String {
    let krate = crate::corpus::lib_name(krate);
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{}",
        indoc::indoc! {"
            //! Generated by `cargo xtask example`. The client and the server of one description,
            //! talking over a real socket.
            //!
            //! This is the only assertion in the project that a generated `send()` builds the request
            //! the description asks for: every other gate checks one side of the wire.
        "}
    );
    let _ = writeln!(
        out,
        "{}",
        indoc::formatdoc! {"
            use std::sync::{{Arc, Mutex}};

            use color_eyre::eyre::{{self, OptionExt as _}};
            use {krate}::{{client, server, types}};
        "}
    );
    out.push_str(RECORDER);
    out.push_str(IMPLEMENTATION);
    out.push_str(TESTS);
    out
}

/// The test double: an `Api` implementation that records what each handler was handed.
const RECORDER: &str = indoc::indoc! {r"
/// What the server saw, so the test can assert on the request rather than only on the reply.
/// Field-by-field rather than holding a `types::Pet`: a generated type carries only the derives
/// the configuration asked for, and `PartialEq` is not one of them by default. Comparing what the
/// server saw against what the client sent is the point, and it does not need the type to be
/// comparable.
#[derive(Debug, Default, Clone, PartialEq)]
struct Seen {
    limit: Option<i64>,
    pet_id: Option<String>,
    probe_id: Option<i64>,
    probe_limit: Option<i64>,
    probe_mode: Option<String>,
    probe_session: Option<i64>,
    probe_body: Option<(i64, String)>,
    photo_note: Option<String>,
    photo_file: Option<String>,
}

/// Cloneable rather than shared behind an `Arc` from outside, because `router` takes the
/// implementation by value and a foreign trait cannot be implemented for `Arc<T>` here anyway.
#[derive(Debug, Default, Clone)]
struct Double {
    seen: Arc<Mutex<Seen>>,
}

impl Double {
    fn record(&self, edit: impl FnOnce(&mut Seen)) {
        let mut seen = match self.seen.lock() {
            Ok(seen) => seen,
            Err(poisoned) => poisoned.into_inner(),
        };
        edit(&mut seen);
    }

    fn seen(&self) -> Seen {
        match self.seen.lock() {
            Ok(seen) => seen.clone(),
            Err(poisoned) => poisoned.into_inner().clone(),
        }
    }
}
"};

/// The `Api` implementation. Spelled out rather than generated, so it reads as a consumer's would.
const IMPLEMENTATION: &str = indoc::indoc! {r#"
impl server::Api for Double {
    async fn list_pets(&self, query: server::ListPetsQuery) -> server::ListPetsResponse {
        self.record(|seen| seen.limit = query.limit);
        // A response position takes the read form of its type. A strict value converts into
        // it, which is how a server built on the strict types answers.
        server::ListPetsResponse::Ok(Box::new(vec![types::Pet {
            id: 1,
            name: "Rex".to_owned(),
            tag: Some("dog".to_owned()),
        }
        .into()]))
    }

    async fn create_pets(&self) -> server::CreatePetsResponse {
        server::CreatePetsResponse::Created(())
    }

    async fn list_pets_paged(
        &self,
        query: server::ListPetsPagedQuery,
    ) -> server::ListPetsPagedResponse {
        // Two pages: the first names a cursor, the second does not.
        let (items, next) = match query.cursor.as_deref() {
            None => (vec![(1, "Rex"), (2, "Tom")], Some("page-2".to_owned())),
            Some(_) => (vec![(3, "Kit")], None),
        };
        server::ListPetsPagedResponse::Ok(Box::new(types::read::PetPage {
            items: Some(
                items
                    .into_iter()
                    .map(|(id, name)| types::read::Pet {
                        id: Some(id),
                        name: Some(name.to_owned()),
                        ..Default::default()
                    })
                    .collect(),
            ),
            next,
            ..Default::default()
        }))
    }

    async fn show_pet_by_id(&self, path: server::ShowPetByIdPath) -> server::ShowPetByIdResponse {
        self.record(|seen| seen.pet_id = Some(path.pet_id.clone()));
        server::ShowPetByIdResponse::Ok(Box::new(types::read::Pet::from(types::Pet {
            id: 7,
            name: path.pet_id,
            tag: None,
        })))
    }

    async fn upload_pet_photo(
        &self,
        path: server::UploadPetPhotoPath,
        body: types::UploadPetPhotoBody,
    ) -> server::UploadPetPhotoResponse {
        self.record(|seen| {
            seen.photo_note = body.note.clone();
            seen.photo_file = Some(body.file.clone());
        });
        // A type only a response yields has no strict form; its read form is written out, and
        // `Default` fills whatever the answer leaves unsaid.
        server::UploadPetPhotoResponse::Created(Box::new(types::read::PhotoUpload {
            pet_id: Some(path.pet_id),
            filename: Some("photo".to_owned()),
            content_type: Some("image/png".to_owned()),
            file_size: Some(body.file.len() as i64),
            note: body.note,
            rating: body.rating,
            ..Default::default()
        }))
    }

    async fn typed_errors(&self, path: server::TypedErrorsPath) -> server::TypedErrorsResponse {
        match path.kind.as_str() {
            "missing" => server::TypedErrorsResponse::NotFound(Box::new(types::read::Error {
                code: Some(404),
                message: Some("missing".to_owned()),
                ..Default::default()
            })),
            "conflict" => server::TypedErrorsResponse::Conflict(Box::new(types::read::Error {
                code: Some(409),
                message: Some("conflict".to_owned()),
                ..Default::default()
            })),
            _ => server::TypedErrorsResponse::NoContent(()),
        }
    }

    async fn download_bytes(&self) -> server::DownloadBytesResponse {
        server::DownloadBytesResponse::Ok(Box::new(vec![0, 255, b'{', b'\n']))
    }

    async fn download_text(&self) -> server::DownloadTextResponse {
        server::DownloadTextResponse::Ok(Box::new(
            "plain text\nthat is not JSON".to_owned(),
        ))
    }

    async fn rejection_probe(
        &self,
        path: server::RejectionProbePath,
        query: server::RejectionProbeQuery,
        header: server::RejectionProbeHeader,
        cookie: server::RejectionProbeCookie,
        body: types::Pet,
    ) -> server::RejectionProbeResponse {
        self.record(|seen| {
            seen.probe_id = Some(path.id);
            seen.probe_limit = Some(query.limit);
            seen.probe_mode = Some(header.x_mode.clone());
            seen.probe_session = Some(cookie.session);
            seen.probe_body = Some((body.id, body.name.clone()));
        });
        server::RejectionProbeResponse::NoContent(())
    }
}
"#};

/// The assertions themselves.
const TESTS: &str = indoc::indoc! {r#"
/// Start the generated server on an ephemeral port and hand back a client pointed at it.
async fn serving() -> eyre::Result<(Double, client::Client)> {
    let double = Double::default();
    let router = server::router(double.clone());
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await?;
    let address = listener.local_addr()?;
    tokio::spawn(async move {
        let _ = axum::serve(listener, router).await;
    });
    Ok((double, client::Client::new(format!("http://{address}"))))
}

/// Start a hand-written raw server so the generated client cannot agree with its own renderer.
async fn raw_serving() -> eyre::Result<client::Client> {
    use axum::http::header::CONTENT_TYPE;
    use axum::routing::get;

    let router = axum::Router::new()
        .route(
            "/download",
            get(|| async {
                (
                    [(CONTENT_TYPE, "application/octet-stream")],
                    vec![0, 255, b'{', b'\n'],
                )
            }),
        )
        .route(
            "/motd",
            get(|| async {
                (
                    [(CONTENT_TYPE, "text/plain")],
                    "plain text\nthat is not JSON",
                )
            }),
        )
        // A vendor that drifted: a required member sent as `null`, a member the description
        // never declared, and a required member missing from one record of the page.
        .route(
            "/pets",
            get(|| async {
                axum::Json(serde_json::json!([
                    {"id": 1, "name": null, "tag": "dog", "color": "brown"},
                    {"id": 2, "tag": "cat"},
                    {"id": 3, "name": "Rex"},
                ]))
            }),
        )
        // A paged listing whose second page has an item that cannot be read: the stream must
        // not skip it quietly.
        .route(
            "/pets/paged",
            get(|query: axum::extract::Query<std::collections::BTreeMap<String, String>>| async move {
                if query.contains_key("cursor") {
                    axum::Json(serde_json::json!({"items": [{"id": 3, "name": "Kit"}, "??"]}))
                } else {
                    axum::Json(serde_json::json!({
                        "items": [{"id": 1, "name": "Rex"}, {"id": 2, "name": "Tom"}],
                        "next": "page-2",
                    }))
                }
            }),
        )
        // A root that is not what the description declares at all.
        .route(
            "/pets/{pet_id}",
            get(|| async { axum::Json(serde_json::json!(["not", "an", "object"])) }),
        );
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await?;
    let address = listener.local_addr()?;
    tokio::spawn(async move {
        let _ = axum::serve(listener, router).await;
    });
    Ok(client::Client::new(format!("http://{address}")))
}

#[test_util::test]
async fn a_query_parameter_survives_the_round_trip() {
    let (double, client) = serving().await?;
    let pets = client
        .list_pets(client::ListPetsParams { limit: Some(3) })
        .send()
        .await?;
    assert_eq!(double.seen().limit, Some(3));
    assert!(!pets.is_degraded(), "{}", pets.degradations());
    assert_eq!(pets.into_value()[0].name.as_deref(), Some("Rex"));

    // And an unset optional parameter arrives unset, rather than as a default the caller never
    // chose — the same rule the client's params and the server's extractor have to agree on.
    let (double, client) = serving().await?;
    let _ = client
        .list_pets(client::ListPetsParams { limit: None })
        .send()
        .await?;
    assert_eq!(double.seen().limit, None);
}

#[test_util::test]
async fn a_path_parameter_survives_the_round_trip() {
    let (double, client) = serving().await?;
    let pet = client
        .show_pet_by_id(client::ShowPetByIdParams {
            pet_id: "a pet/with slashes".to_owned(),
        })
        .send()
        .await?;
    // Percent-encoded on the way out and decoded on the way in, which is the pair of rules a
    // template variable actually depends on.
    assert_eq!(double.seen().pet_id.as_deref(), Some("a pet/with slashes"));
    assert_eq!(pet.into_value().name.as_deref(), Some("a pet/with slashes"));
}

#[test_util::test]
async fn every_parameter_location_arrives_at_once() {
    // The one operation with a path parameter, a query parameter, a header, a cookie and a body
    // together. Four locations is where a renderer that puts one in the wrong place still passes
    // every other gate.
    let (double, client) = serving().await?;
    let sent = types::Pet {
        id: 42,
        name: "Probe".to_owned(),
        tag: None,
    };
    let expected = (sent.id, sent.name.clone());
    client
        .rejection_probe(client::RejectionProbeParams {
            id: 9,
            limit: 11,
            x_mode: "strict".to_owned(),
            session: 1234,
            body: sent,
        })
        .send()
        .await?;
    let seen = double.seen();
    assert_eq!(seen.probe_id, Some(9));
    assert_eq!(seen.probe_limit, Some(11));
    assert_eq!(seen.probe_mode.as_deref(), Some("strict"));
    assert_eq!(seen.probe_session, Some(1234));
    assert_eq!(seen.probe_body, Some(expected));
}

#[test_util::test]
async fn a_multipart_body_survives_the_round_trip() {
    // The writer and the reader are the same rule read from two ends, and this is the only place
    // both ends actually run.
    let (double, client) = serving().await?;
    let reply = client
        .upload_pet_photo(client::UploadPetPhotoParams {
            pet_id: 5,
            body: types::UploadPetPhotoBody {
                file: "not really a png".to_owned(),
                note: Some("a note".to_owned()),
                rating: Some(4),
            },
        })
        .send()
        .await?;
    let seen = double.seen();
    assert_eq!(seen.photo_file.as_deref(), Some("not really a png"));
    assert_eq!(seen.photo_note.as_deref(), Some("a note"));
    assert_eq!(reply.into_value().pet_id, Some(5));
}

#[test_util::test]
async fn a_declared_error_status_arrives_as_the_typed_error_it_was_sent_as() {
    // The client's status match and the server's response enum come from one record, and this is
    // the assertion that they agree about which arm a status lands in.
    let (_, client) = serving().await?;
    let error = client
        .typed_errors(client::TypedErrorsParams {
            kind: "conflict".to_owned(),
        })
        .send()
        .await
        .err()
        .ok_or_eyre("a declared failure")?;
    let message = format!("{error:?}");
    assert!(message.contains("409"), "{message}");
    assert!(message.contains("conflict"), "{message}");

    let (_, client) = serving().await?;
    client
        .typed_errors(client::TypedErrorsParams {
            kind: "neither".to_owned(),
        })
        .send()
        .await?;
}

#[test_util::test]
async fn the_client_reads_non_json_response_bodies_from_the_raw_wire() {
    let client = raw_serving().await?;

    let bytes = client.download_bytes().send().await?.into_value();
    assert_eq!(bytes, [0, 255, b'{', b'\n']);

    let text = client.download_text().send().await?.into_value();
    assert_eq!(text, "plain text\nthat is not JSON");
}

/// The Hypofy case: a payload the description no longer matches decodes as far as it allows,
/// with every deviation reported by its place in the description rather than failing the call.
#[test_util::test]
async fn a_drifted_response_decodes_as_far_as_it_can_and_says_what_it_tolerated() {
    let client = raw_serving().await?;
    let pets = client
        .list_pets(client::ListPetsParams { limit: None })
        .send()
        .await?;
    assert!(pets.is_degraded());
    let report = pets.degradations().clone();
    let pets = pets.into_value();
    assert_eq!(pets.len(), 3);
    assert_eq!(pets[0].name, None);
    assert_eq!(pets[0].tag.as_deref(), Some("dog"));
    assert_eq!(pets[0].extra.get("color"), Some(&serde_json::json!("brown")));
    assert_eq!(pets[1].name, None);
    assert_eq!(pets[2].name.as_deref(), Some("Rex"));

    // One entry per (site, kind), however many records shared the drift, each naming the
    // pointer an override would use.
    // Spelled from the type's own constant: nothing copied out of the generated source.
    let name = types::Site {
        member: Some("name"),
        ..types::read::Pet::SITE
    };
    assert_eq!(name.origin, "/components/schemas/Pet");
    let kinds: Vec<types::DegradationKind> = report.at(&name).map(|entry| entry.kind).collect();
    assert_eq!(
        kinds,
        [types::DegradationKind::RequiredAbsent, types::DegradationKind::NullNotAllowed]
    );
    let undeclared = report
        .iter()
        .find(|entry| entry.kind == types::DegradationKind::UndeclaredMember)
        .ok_or_eyre("the undeclared member is reported")?;
    assert_eq!(undeclared.site.type_name, "Pet");
    assert_eq!(undeclared.samples, ["color"]);
    let rendered = report.to_string();
    assert!(rendered.contains("/components/schemas/Pet/properties/name"), "{rendered}");
    assert_eq!(report.len(), 3, "{rendered}");

    // A payload that is not the declared shape at the root has no value to hand back.
    let error = client
        .show_pet_by_id(client::ShowPetByIdParams { pet_id: "1".to_owned() })
        .send()
        .await
        .err()
        .ok_or_eyre("a root of the wrong shape is refused")?;
    assert!(matches!(error, client::Error::Decode(_)), "{error:?}");

    // The same read type through plain serde: the same value, without the report.
    let parsed: types::read::Pet = serde_json::from_str("{\"id\": 4, \"extra\": true}")?;
    assert_eq!(parsed.id, Some(4));
    assert_eq!(parsed.name, None);
    assert_eq!(parsed.extra.get("extra"), Some(&serde_json::json!(true)));
    // And written back as it arrived: no invented `null` for what was missing.
    assert_eq!(serde_json::to_string(&parsed)?, "{\"id\":4,\"extra\":true}");
}

/// A stream follows the cursor through read forms, and a page degraded on the path it walks —
/// here an item that cannot be read — ends the stream with an error rather than skipping.
#[test_util::test]
async fn a_stream_walks_read_forms_and_refuses_a_degraded_page() {
    use futures_util::TryStreamExt as _;

    let (_, client) = serving().await?;
    let names: Vec<String> = client
        .list_pets_paged(client::ListPetsPagedParams { cursor: None })
        .stream()
        .map_ok(|pet| pet.name.unwrap_or_default())
        .try_collect()
        .await?;
    assert_eq!(names, ["Rex", "Tom", "Kit"]);

    let client = raw_serving().await?;
    let mut stream = std::pin::pin!(
        client
            .list_pets_paged(client::ListPetsPagedParams { cursor: None })
            .stream()
    );
    let mut names = Vec::new();
    let error = loop {
        match stream.try_next().await {
            Ok(Some(pet)) => names.push(pet.name.unwrap_or_default()),
            Ok(None) => eyre::bail!("the degraded page should have ended the stream"),
            Err(error) => break error,
        }
    };
    assert_eq!(names, ["Rex", "Tom"]);
    let client::Error::DegradedPage(report) = error else {
        eyre::bail!("expected a degraded page, got {error:?}");
    };
    let rendered = report.to_string();
    assert!(rendered.contains("PetPage.items"), "{rendered}");
    assert!(rendered.contains("could not be read"), "{rendered}");
}

/// The observer sees every degraded response once, with the operation it answered and the same
/// report the response carries; a clean response never reaches it.
#[test_util::test]
async fn an_observer_is_told_about_every_degraded_response() {
    let seen: Arc<Mutex<Vec<(String, u16, String)>>> = Arc::default();
    let client = raw_serving().await?.observe({
        let seen = Arc::clone(&seen);
        move |degraded: client::Degraded<'_>| {
            if let Ok(mut seen) = seen.lock() {
                seen.push((
                    degraded.operation.to_owned(),
                    degraded.status.as_u16(),
                    degraded.degradations.to_string(),
                ));
            }
        }
    });
    let pets = client
        .list_pets(client::ListPetsParams { limit: None })
        .send()
        .await?;
    let text = client.download_text().send().await?;
    assert!(!text.is_degraded());
    let seen = seen.lock().map_err(|_| eyre::eyre!("poisoned"))?.clone();
    assert_eq!(seen.len(), 1, "{seen:?}");
    assert_eq!(seen[0].0, "list_pets");
    assert_eq!(seen[0].1, 200);
    assert_eq!(seen[0].2, pets.degradations().to_string());
}

#[test_util::test]
async fn the_server_writes_declared_non_json_bodies_and_content_types() {
    let (_, client) = serving().await?;
    let raw = reqwest::Client::new();

    let bytes = raw
        .get(format!("{}/download", client.base_url()))
        .send()
        .await?;
    assert_eq!(
        bytes.headers().get(reqwest::header::CONTENT_TYPE),
        Some(&reqwest::header::HeaderValue::from_static(
            "application/octet-stream"
        ))
    );
    assert_eq!(bytes.bytes().await?.as_ref(), [0, 255, b'{', b'\n']);

    let text = raw
        .get(format!("{}/motd", client.base_url()))
        .send()
        .await?;
    assert_eq!(
        text.headers().get(reqwest::header::CONTENT_TYPE),
        Some(&reqwest::header::HeaderValue::from_static("text/plain"))
    );
    assert_eq!(text.text().await?, "plain text\nthat is not JSON");
}

#[test_util::test]
async fn a_request_the_description_does_not_describe_is_rejected_in_one_place() {
    // Not sent through the generated client, because the generated client cannot build a request
    // this wrong — which is the point of the params struct. The rejection envelope exists for
    // every *other* client, and this is what it answers with.
    let (_, client) = serving().await?;
    let raw = reqwest::Client::new();
    let response = raw
        .post(format!("{}/rejection-probe/9?limit=11", client.base_url()))
        .header("x-mode", "strict")
        .json(&types::Pet { id: 1, name: "p".to_owned(), tag: None })
        .send()
        .await?;
    assert_eq!(response.status(), 400);
    let body: serde_json::Value = response.json().await?;
    let message = body["message"].as_str().unwrap_or_default();
    assert!(message.contains("session"), "{body}");
    assert!(message.contains("rejection_probe"), "{body}");
}
"#};
