//! The wire differential: every operation of a document, sent by its generated client to its
//! generated server.
//!
//! `xtask example` is this exact idea for one hand-written document; the probe is the generated
//! form of it for any document. The plan — which setters to call, what the double answers, which
//! operations cannot be driven and why — comes from `progeny::harness::probe`, built from the same
//! frozen contracts the renderers read. What is asserted per operation:
//!
//! * the request the client builds **extracts cleanly** in the server — no rejection, which is the
//!   failure mode both of the example crate's first-minute catches surfaced as;
//! * every optional parameter the driver set **arrives `Some`** in the handler, which catches a
//!   parameter dropped without a rejection;
//! * the declared response **decodes back** in the client, with the declared status.
//!
//! Skipped operations are counted and named — a probe that silently narrows its corpus reads as
//! "covered" when it is not.

use std::fmt::Write as _;

use anyhow::{Context, Result, bail};
use clap::Args as ClapArgs;
use progeny::harness::{Probe, ProbeOp};

#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Corpus documents to probe. Defaults to the quick tier.
    #[arg(value_name = "SPEC")]
    specs: Vec<String>,

    /// Write the probe crates and stop, without compiling or running anything.
    #[arg(long)]
    generate_only: bool,

    /// Which serde strategy to generate with, rather than the configuration default.
    ///
    /// A serde-path defect that shows up only over a socket — a rejection rather than a payload
    /// mismatch — is exactly this gate's class, and until this flag the request-sending gates
    /// only ever drove the default strategy.
    #[arg(long, value_name = "STRATEGY")]
    serde: Option<crate::corpus::SerdeChoice>,
}

pub fn run(args: &Args) -> Result<()> {
    crate::generated::require_cargo()?;

    let wanted: Vec<String> = if args.specs.is_empty() {
        crate::corpus::quick_tier()?
    } else {
        args.specs.clone()
    };
    let documents = crate::corpus::selected(&wanted)?;

    let mut failures = 0usize;
    for (spec, bytes) in &documents {
        let name = &spec.name;
        let mut config = crate::corpus::config_for(spec);
        if let Some(choice) = args.serde {
            config.serde_impl = choice.into();
        }

        let plan = progeny::harness::probe(bytes, &config)
            .with_context(|| format!("planning the probe for {name}"))?;
        let output =
            progeny::generate(bytes, &config).with_context(|| format!("generating {name}"))?;
        let directory = crate::generated::write(&format!("probe-{name}"), &output)?;

        crate::generated::write_wire_test(
            &directory,
            "probe.rs",
            &render(&config.package.name, &plan),
        )?;

        let driven = plan
            .operations
            .iter()
            .filter(|operation| operation.skip.is_none())
            .count();
        let skipped: Vec<&ProbeOp> = plan
            .operations
            .iter()
            .filter(|operation| operation.skip.is_some())
            .collect();
        println!(
            "probe: {name}: {driven} operations driven, {} skipped",
            skipped.len()
        );
        for operation in &skipped {
            println!(
                "         skip {}: {}",
                operation.method,
                operation.skip.as_deref().unwrap_or_default()
            );
        }
        if args.generate_only {
            println!("         written but not run: {directory}/tests/probe.rs");
            continue;
        }

        let run = crate::generated::cargo(&directory)
            .args(["test", "--quiet", "--all-features", "--test", "probe"])
            .output()
            .context("running the probe")?;
        if !run.status.success() {
            failures += 1;
            println!(
                "probe: {name} FAILED\n{}{}",
                String::from_utf8_lossy(&run.stdout),
                String::from_utf8_lossy(&run.stderr)
            );
        }
    }

    if failures > 0 {
        bail!("{failures} documents have a client and server that disagree on the wire");
    }
    println!(
        "probe: every driven operation of {} documents extracts cleanly and answers with its \
         declared status",
        documents.len()
    );
    Ok(())
}

/// The probe test file: the double implementing every servable operation, then one driver test per
/// driven one.
fn render(krate: &str, plan: &Probe) -> String {
    let krate = crate::corpus::lib_name(krate);
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Generated by `cargo xtask probe`. Every servable operation of this description,\n\
         //! sent by the generated client to the generated server over a socket.\n\
         #![allow(unused_variables, unused_imports, deprecated, clippy::all)]\n\n\
         use {krate}::{{client, server, types}};\n\n\
         /// Read a synthesized value out of its JSON spelling.\n\
         fn value<T: serde::de::DeserializeOwned>(json: &str) -> T {{\n\
         \x20   serde_json::from_str(json).expect(\"a synthesized value matches its own contract\")\n\
         }}\n\n\
         #[derive(Debug, Clone)]\n\
         struct Double;\n\n\
         async fn serving() -> client::Client {{\n\
         \x20   let router = server::router(Double);\n\
         \x20   let listener = tokio::net::TcpListener::bind(\"127.0.0.1:0\")\n\
         \x20       .await\n\
         \x20       .expect(\"an ephemeral port\");\n\
         \x20   let address = listener.local_addr().expect(\"a bound address\");\n\
         \x20   tokio::spawn(async move {{\n\
         \x20       let _ = axum::serve(listener, router).await;\n\
         \x20   }});\n\
         \x20   client::Client::new(format!(\"http://{{address}}\"))\n\
         }}\n\n\
         impl server::Api for Double {{"
    );
    for operation in &plan.operations {
        out.push_str(&handler(operation));
    }
    out.push_str("}\n");
    for operation in &plan.operations {
        if operation.skip.is_none()
            && let Some(answer) = &operation.response.answer
        {
            out.push_str(&driver(operation, answer));
        }
    }
    out
}

/// One trait method on the double: presence assertions, then the synthesized response.
fn handler(operation: &ProbeOp) -> String {
    let mut out = String::new();
    let mut arguments = String::new();
    for group in &operation.groups {
        let _ = write!(arguments, ", {}: server::{}", group.arg, group.ty);
    }
    if let Some(body) = &operation.body {
        // An optional body reaches the trait as an `Option`, exactly like an optional parameter
        // reaches its group struct.
        if body.required {
            let _ = write!(arguments, ", body: {}", body.ty);
        } else {
            let _ = write!(arguments, ", body: ::std::option::Option<{}>", body.ty);
        }
    }
    let _ = write!(
        out,
        "\n    async fn {}(&self{arguments}) -> server::{} {{\n",
        operation.method, operation.response.enum_name
    );
    if operation.skip.is_some() {
        let _ = writeln!(out, "        unimplemented!(\"skipped by the probe plan\")");
        out.push_str("    }\n");
        return out;
    }
    // A plan with no skip carries an answer; the type makes reading a sentinel impossible, and
    // this keeps an answerless method honest if that invariant ever moves.
    let Some(answer) = &operation.response.answer else {
        let _ = writeln!(
            out,
            "        unimplemented!(\"the plan carries no answer\")"
        );
        out.push_str("    }\n");
        return out;
    };
    for group in &operation.groups {
        for field in &group.optional_fields {
            let _ = writeln!(
                out,
                "        assert!({}.{field}.is_some(), \"`{field}` was set by the driver and \
                 dropped on the way to the handler\");",
                group.arg
            );
        }
    }
    if operation.body.as_ref().is_some_and(|body| !body.required) {
        let _ = writeln!(
            out,
            "        assert!(body.is_some(), \"the body was set by the driver and dropped on \
             the way to the handler\");"
        );
    }
    let _ = writeln!(
        out,
        "        server::{}::{}(value::<{}>({}))",
        operation.response.enum_name,
        answer.variant,
        answer.ty,
        json_literal(&answer.json),
    );
    out.push_str("    }\n");
    out
}

/// One driver test: set every parameter, send, and expect the declared status back.
fn driver(operation: &ProbeOp, answer: &progeny::harness::ProbeAnswer) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        "\n#[tokio::test]\nasync fn probe_{}() {{\n    let client = serving().await;\n    \
         let response = client.{}()",
        operation.method, operation.method
    );
    for setter in &operation.setters {
        let _ = write!(
            out,
            "\n        .{}(value::<{}>({}))",
            setter.setter,
            setter.ty,
            json_literal(&setter.json)
        );
    }
    if let Some(body) = &operation.body {
        let _ = write!(
            out,
            "\n        .body(value::<{}>({}))",
            body.ty,
            json_literal(&body.json)
        );
    }
    let _ = write!(
        out,
        "\n        .send()\n        .await\n        .unwrap_or_else(|error| \
         panic!(\"the server rejected what the client built: {{error:?}}\"));\n    \
         assert_eq!(response.status().as_u16(), {});\n}}\n",
        answer.status
    );
    out
}

/// A JSON value as a Rust string literal, whatever it contains.
fn json_literal(json: &str) -> String {
    format!("{json:?}")
}
